### ISSUE TITLE
插件安装问题

### ISSUE THREAD

**Issue by gcphym** [kenzok8/openwrt-packages#103]
比如luci-app-jd-dailybonus这个插件 在lede/package/lean 里面也有 把这个库整个git到 lede/package之后 后面安装的时候菜单里是会显示两个？还是会覆盖？如果这两个插件版本不一样又会怎么样？

**Comment by kenzok8** [comment]
一般会覆盖，但是不建议两个package 下两个jd-dailybonus

**Comment by gcphym** [comment]
请问这里的passwall和这个是一样的吗 https://github.com/xiaorouji/openwrt-passwall
