### ISSUE TITLE
请问：我如果想单独拉取一个插件，src-git 后边要怎么填写？

### ISSUE THREAD

**Issue by aotuitx** [kenzok8/openwrt-packages#104]
如题：
`src-git kenzo https://github.com/kenzok8/openwrt-packages`

**Comment by kenzok8** [comment]
1、先去了解src-git的用法
2、单独拉取某个仓库里的源码 比如passwall
svn co https://github.com/kenzok8/openwrt-packages/trunk/luci-app-passwall

**Comment by aotuitx** [comment]
> 1，先去了解src-git的用法
> 2，单独拉取某个仓库​​里的源码例如passwall
> svn co https://github.com/kenzok8/openwrt-packages/trunk/luci-app-passwall

谢谢。
