### ISSUE TITLE
编译出错, 提示 fatal: No url found for submodule path 'lua-maxminddb' in .gitmodules

### ISSUE THREAD

**Issue by DemonJun** [kenzok8/openwrt-packages#108]
Collecting target info: doneUpdating feed 'kenzo' from 'https://github.com/kenzok8/openwrt-packages' ...
Cloning into './feeds/kenzo'...
fatal: No url found for submodule path 'lua-maxminddb' in .gitmodules
failed.

**Comment by WYC-2020** [comment]
作者文件夹文件漏提交了

**Comment by binbooly** [comment]
遇到同一问题，无法继续编译。

**Comment by zhangsean** [comment]
俺也一样！

**Comment by WYC-2020** [comment]
修复一下就是了，那么简单

**Comment by 892947707** [comment]
> 修复一下就是了，那么简单

辣么怎么修复呢？方便说一下吗

**Comment by kenzok8** [comment]
已修复，./scripts/feeds clean
清除下，重新拉取就行了！

**Comment by binbooly** [comment]
牛批。。。
