### ISSUE TITLE
xray报错啊啊啊

### ISSUE THREAD

**Issue by xyl94k** [kenzok8/openwrt-packages#114]
Configuring sysfsutils.
 * check_data_file_clashes: Package xray-core wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/bin/v2ray
Configuring shellsync.
	But that file is already provided by package  * v2ray
Configuring jshn.
 * opkg_install_cmd: Cannot install package luci-app-passwall.
Configuring netifd.
 * check_data_file_clashes: Package xray-core wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/bin/v2ray
Configuring ubox.
	But that file is already provided by package  * v2ray
Configuring procd.
 * opkg_install_cmd: Cannot install package xray-core.

**Comment by kenzok8** [comment]
https://github.com/kenzok8/openwrt-packages/issues/111#issuecomment-774183165
