### ISSUE TITLE
2020.5.1编译固件提示passwall出错（已安装好依赖）package makefile :65

### ISSUE THREAD

**Issue by wqzxhpx** [kenzok8/openwrt-packages#12]
![捕获](https://user-images.githubusercontent.com/32302128/80789130-a87c0000-8bbd-11ea-806b-a7059937d8f5.PNG)

**Comment by kenzok8** [comment]
看报错是kcp-tun，是否除了ssr或者passwall的kcp-tun，还选择了luci的kcp

**Comment by wqzxhpx** [comment]
已解决，重新编译内核
