### ISSUE TITLE
bypass报错v2ray

### ISSUE THREAD

**Issue by ccc919** [kenzok8/openwrt-packages#121]
Create index file './feeds/small.index' 
WARNING: Makefile 'package/feeds/kenzo/luci-app-bypass/Makefile' has a dependency on 'v2ray', which does not exist
Installing all packages from feed packages.

**Comment by kenzok8** [comment]
默认就是用的xray, 至于v2ray并不是bypass的必选依赖,，正常不会影响编译的

**Comment by ccc919** [comment]
好的谢谢
