### ISSUE TITLE
最近更新的版本和在线编译冲突近期可能不能在线编译了。

### ISSUE THREAD

**Issue by zhaode2019** [kenzok8/openwrt-packages#129]

**Comment by Carrjiang** [comment]
朋友，你至少发个log出来吧。。。我最近一周没一个报错啊。。。

**Comment by zhaode2019** [comment]
[image: 屏幕截图 2021-03-07 053059.png]

Carrjiang <notifications@github.com> 于2021年3月6日周六 上午2:28写道：

**Comment by zhaode2019** [comment]
有附件，里面有所有要用的东西 。

hellow come on f <zhaode88888@gmail.com> 于2021年3月7日周日 上午5:31写道：
