### ISSUE TITLE
small出问题了

### ISSUE THREAD

**Issue by brianzc0306** [kenzok8/openwrt-packages#133]
Create index file './feeds/small.index' 
grep: feeds/small/Makefile:$(eval: 没有那个文件或目录
grep: $(call: 没有那个文件或目录
grep: BuildPackage,$(PKG_NAME)))/Makefile: 没有那个文件或目录
/home/zhouchao/lede/feeds/small.tmp/info/.files-packageinfo.mk:1: *** 目标模式不含有“%”。 停止。
Collecting target info: done

**Comment by haozi4098** [comment]
我也出现了这种问题

**Comment by kenzok8** [comment]
rm -rf ./feeds && ./scripts/feeds update -a && ./scripts/feeds install -a && rm -rf ./tmp && make menuconfig
