### ISSUE TITLE
支持删除bypass

### ISSUE THREAD

**Issue by Netflixxp** [kenzok8/openwrt-packages#134]
高手自己添加，小白一堆问题，用成熟的插件更好

**Comment by qx86936007** [comment]
请问有bypass的链接吗？我想自己添加编译。谢谢！！

**Comment by tyronewoo** [comment]
> 请问有bypass的链接吗？我想自己添加编译。谢谢！！

cd lede/package
git clone https://github.com/garypang13/luci-app-bypass
git clone https://github.com/garypang13/smartdns-le
make menuconfig
之后就可以编译了
