### ISSUE TITLE
请问有bypass的链接吗？我想自己添加编译。谢谢！！

### ISSUE THREAD

**Issue by qx86936007** [kenzok8/openwrt-packages#137]
请问有bypass的链接吗？我想自己添加编译。谢谢！！

**Comment by kenzok8** [comment]
https://github.com/garypang13/luci-app-bypass.git

**Comment by lexin8** [comment]
你连链接都不会找，你还想编译成功？你心真大

**Comment by tyronewoo** [comment]
老大能否重新加入bypass，我用bypass留学打开国内或者国外网页的速度比vssr和ssr+以及passwall要快很多。
