### ISSUE TITLE
luci-app-passwall 删了吗？

### ISSUE THREAD

**Issue by michealhansun** [kenzok8/openwrt-packages#142]
luci-app-passwall 删了吗？

**Comment by ma20at** [comment]
> luci-app-passwall 删了吗？

应该是删除了，你可以回退到上一个版本就，没事别更新
ubt20:~/openwrt/lede/package/openwrt-packages$git reflog
1ccaee0 (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: pull: Fast-forward
3455496 HEAD@{1}: pull: Fast-forward
ubt20:~/openwrt/lede/package/openwrt-packages$ git reset --hard HEAD@{1}

**Comment by michealhansun** [comment]
听说新版本可以订阅vless，今天看到又加回来了，不过昨天已经用“xiaorouji”的仓库编译好了
