### ISSUE TITLE
v2ray-plugin 编译失败

### ISSUE THREAD

**Issue by jiahanbryant** [kenzok8/openwrt-packages#147]
Hi Guys,
今天在最新的repo编译，似乎不能完成了。
```
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-ssr-plus:
 *      v2ray-plugin
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
package/Makefile:65: recipe for target 'package/install' failed
```
看起来像是和这个commit有关系：
```
commit d96a2e78f7095f9d11c9abbfae487b4c8ef8b7d9
Author: coolsnowwolf <coolsnowwolf@gmail.com>
Date:   Sun Apr 18 09:55:04 2021 +0800

    v2ray-plugin: move source
```
我使用的是coolsnowwolf的repo，来编译。
ideas?

Thanks,

**Comment by kenzok8** [comment]
是你的问题吧，我云编译能正常呢

**Comment by jiahanbryant** [comment]
hmmm...我前两天（4月17日）编译都还正常，我今天运行了：
·./scripts/feeds update -a && ./scripts/feeds install -a·
然后再`make defconfig`就会产生这个提示：
```
WARNING: Makefile 'package/feeds/kenzo/luci-app-passwall/Makefile' has a dependency on 'v2ray-plugin', which does not exist
WARNING: Makefile 'package/feeds/kenzo/luci-app-ssr-plus/Makefile' has a dependency on 'v2ray-plugin', which does not exist
```
编译就会失败。或者我再试试。。

**Comment by jiahanbryant** [comment]
@kenzok8 你可以重现吗？因为我的还是有这个问题。

**Comment by CuteTony** [comment]
+1

**Comment by chenyg0911** [comment]
+1

**Comment by chenyg0911** [comment]
comments the line  which need V2ray-plugin in:
`$Lededir/feeds/helloworld/luci-app-ssr-plus/Makefile` & `$Lededir/feeds/kenzo/luci-app-passwall/Makefile` 
![2021-04-22 14-49-32](https://user-images.githubusercontent.com/16010372/115668819-2494c800-a37a-11eb-8f46-61336cfb3b0d.png)

then Run: ./scripts/feeds update -a && ./scripts/feeds install -a

**Comment by jiahanbryant** [comment]
> comments the line which need V2ray-plugin in:
> `$Lededir/feeds/helloworld/luci-app-ssr-plus/Makefile` & `$Lededir/feeds/kenzo/luci-app-passwall/Makefile`
> ![2021-04-22 14-49-32](https://user-images.githubusercontent.com/16010372/115668819-2494c800-a37a-11eb-8f46-61336cfb3b0d.png)
> 
> then Run: ./scripts/feeds update -a && ./scripts/feeds install -a

我没有仔细check这个build的architecture,如果我把这个comment out，意味着我没有来v2ray feature？

**Comment by chenyg0911** [comment]
lean默认用的xray客户端，应该没影响。我用vless正常。

**Comment by jiahanbryant** [comment]
> lean默认用的xray客户端，应该没影响。我用ssrp vless正常。passwall没试过。

Thanks bro, just to be clear, so you still have the option when trying to create a new server node?
![image](https://user-images.githubusercontent.com/53395918/115979992-d2db8000-a5bb-11eb-9b43-7dc76085f2d8.png)

**Comment by chenyg0911** [comment]
> > lean默认用的xray客户端，应该没影响。我用ssrp vless正常。passwall没试过。
> 
> Thanks bro, just to be clear, so you still have the option when trying to create a new server node?
> ![image](https://user-images.githubusercontent.com/53395918/115979992-d2db8000-a5bb-11eb-9b43-7dc76085f2d8.png)

![2021-04-25 16-32-56屏幕截图](https://user-images.githubusercontent.com/16010372/115986686-0c27e600-a5e4-11eb-87c9-b4e9510e8b0a.png)

**Comment by jiahanbryant** [comment]
> > > lean默认用的xray客户端，应该没影响。我用ssrp vless正常。passwall没试过。
> > 
> > 
> > Thanks bro, just to be clear, so you still have the option when trying to create a new server node?
> > ![image](https://user-images.githubusercontent.com/53395918/115979992-d2db8000-a5bb-11eb-9b43-7dc76085f2d8.png)
> 
> ![2021-04-25 16-32-56屏幕截图](https://user-images.githubusercontent.com/16010372/115986686-0c27e600-a5e4-11eb-87c9-b4e9510e8b0a.png)

ok 谢谢。这个早晚要修复的吧，我关闭了。
