### ISSUE TITLE
源缺少依赖,编译失败

### ISSUE THREAD

**Issue by la8896** [kenzok8/openwrt-packages#153]
make: *** [world] Error 1
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
/workdir/openwrt/include/toplevel.mk:222: recipe for target 'world' failed
WARNING: Makefile 'package/feeds/kenzo/luci-app-vssr/Makefile' has a dependency on 'shadowsocksr-libev-alt', which does not exist
WARNING: Makefile 'package/feeds/kenzo/luci-app-vssr/Makefile' has a dependency on 'shadowsocksr-libev-server', which does not exist

**Comment by aepub** [comment]
遇到同样的问题！不知道解决办法怎样！
