### ISSUE TITLE
小白新人新人求助openwrt-packages放置目录问题

### ISSUE THREAD

**Issue by carlyang1986** [kenzok8/openwrt-packages#16]
我最近刚刚入门编译L大的固件，看到您的openwrt包想问一下openwrt-package这个包应该是在lede的package目录下还是在package/lean目录下，如果是在package目录下make menuconfig好像找不到相应的软件包选项，在lean目录下可以看到，但是和readme的教程不一样，而且我也同时将small依赖包放入lean的目录，但是makefile的时候也没有看到，麻烦大神耐心解答。

**Comment by kenzok8** [comment]
在lede的package目录下
路径我说明了呢

**Comment by kenzok8** [comment]
lede/package/  这个路径

然后运行git clone ....................

Git clone后需要 运行

 ./scripts/feeds update -a && ./scripts/feeds install -a

然后在运行mane menuconfig  这些是基本操作，图形编译就能看到你添加的luci了，希望对你有帮助

**Comment by Memorainer** [comment]
@kenzok8 我看有几个第三方插件，有的是要求放在/lede/package/下，有的又是放到/lede/package/lean/下，这有什么不同吗？

**Comment by carlyang1986** [comment]
万分感谢大佬回复
