### ISSUE TITLE
adguard 改41行后其他易燃报错

### ISSUE THREAD

**Issue by rq1025330** [kenzok8/openwrt-packages#163]
![image](https://user-images.githubusercontent.com/52870887/120064466-dcff0b80-c09e-11eb-8a6a-b8f000e76868.png)

**Comment by kenzok8** [comment]
feeds文件里留存的是老文件，另外DL文件家下载的包也可能是老文件，我编译很正常，
使用下面命令后再重头编译一下
rm -rf ./feeds
make distclean
