### ISSUE TITLE
 lienol大源码下编译的v2ray-plugin插件不可用

### ISSUE THREAD

**Issue by lxhao61** [kenzok8/openwrt-packages#17]
最近折腾SS的v2ray-plugin应用， 在lienol大源码下编译，无论passwall或ShadowsocksR Plus+加上v2ray-plugin插件都发现不可用。状况：SS单独使用无问题，一旦关联启用v2ray-plugin插件，SS无法启动（运行状态中TCP没有运行）。

**Comment by kenzok8** [comment]
高级设置里守护进程开启，保存。刷新下看看

**Comment by lxhao61** [comment]
刚按照你建议试了，无论怎么刷新都不行。

**Comment by kenzok8** [comment]
我特意去开启，没问题，请检查固件

**Comment by lxhao61** [comment]
大神，判断固件（斐讯K3）有问题，是对的！谢谢测试及告知！
但我随后测试反复折腾测试，发现同样lienol大源码下编译的v2ray-plugin及其它完全相同插件，仅斐讯K3此插件有问题，其它如新路由3(D2)等无问题，一切正常。不知道怎么怎样？
怀疑：是arm架构的K3没有开启FPU？但编译的V2RAY插件可以用呀？另外arm架构有FPU开启选项不，怎么开启？等，搞不懂了！

**Comment by lxhao61** [comment]
其它测试发现（编译斐讯K3固件-默认配置，仅修改增减插件编译。）：
1、Lean大源码下编译的passwall（含v2ray-plugin插件）客户端，连V2RAY都无法启动。
2、Lean大源码下编译的ShadowsocksR Plus+（含v2ray-plugin插件）客户端，全部正常。

**Comment by lxhao61** [comment]
v2ray-plugin源码配置问题，已更新解决。
