### ISSUE TITLE
ssr-plus分流问题

### ISSUE THREAD

**Issue by lexin8** [kenzok8/openwrt-packages#18]
ssr-plus编译使用默认参数开启后，闲鱼APP会被检测使用VPN 貌似被认为是墙了！

**Comment by kenzok8** [comment]
一般这情况是dns作祟，请检查是否另外开启了代理软件，或者dns设置

**Comment by lexin8** [comment]
经过多天的测试，也更新最新版本，很奇怪，部分手机会出现，一旦关闭或者指定该IP不走科学上网就不会出现咸鱼被墙问题，其他网站APP都没有发现这种情况、
测试就经过是SSR问题，很有可能是SSR里面的DNS分流协议问题。
![1](https://user-images.githubusercontent.com/61616502/85859896-761f0580-b7f0-11ea-9adf-707c702573ea.png)
