### ISSUE TITLE
luci-app-vssr 缺少依赖

### ISSUE THREAD

**Issue by hugoyue** [kenzok8/openwrt-packages#181]
luci-app-vssr 缺少依赖 v2ray-plugin

**Comment by halibw** [comment]
> luci-app-vssr 缺少依赖 v2ray-plugin

ssr-plus也是缺少v2ray-plugin

**Comment by kenzok8** [comment]
xray里已经包含v2ray了，且编译提示缺少v2ray-pluginv也是无关紧要，此问题早先已经回复多次，或者你也可以去我的完整库拉取
https://github.com/kenzok8/small-package.git

**Comment by hugoyue** [comment]
> xray里已经包含v2ray了，且编译提示缺少v2ray-pluginv也是无关紧要，此问题早先已经回复多次，或者你也可以去我的完整库拉取
> https://github.com/kenzok8/small-package.git

好的 谢谢😄
