### ISSUE TITLE
依赖有问题获取不到

### ISSUE THREAD

**Issue by seanlxx** [kenzok8/openwrt-packages#183]
WARNING: Makefile 'package/feeds/kenzo/luci-app-passwall/Makefile' has a dependency on 'v2ray-plugin', which does not exist
WARNING: Makefile 'package/feeds/kenzo/luci-app-ssr-plus/Makefile' has a dependency on 'v2ray-plugin', which does not exist

**Comment by HanzChen** [comment]
遇到同样的问题

**Comment by Sauryc** [comment]
遇到同样的问题  希望尽快补救

**Comment by aepub** [comment]
今天也遇到相同的问题！

**Comment by kenzok8** [comment]
xray里已经包含v2ray了，且编译提示缺少v2ray-pluginv也是无关紧要，此问题早先已经回复多次，或者你也可以去我的完整库拉取
https://github.com/kenzok8/small-package.git
