### ISSUE TITLE
smart DNS

### ISSUE THREAD

**Issue by seaks** [kenzok8/openwrt-packages#186]
lean 固件添加smartdns  编译完.不显示.

什么原因

**Comment by reaiyaogun** [comment]
[https://github.com/kenzok8/openwrt-packages/commit/751bb056f52aff98056c0ba003d175041793fc4c](url)
这个commit吧luasrc目录给删了，导致不兼容18.06了

**Comment by seaks** [comment]
> [https://github.com/kenzok8/openwrt-packages/commit/751bb056f52aff98056c0ba003d175041793fc4c](url)
> 这个commit吧luasrc目录给删了，导致不兼容18.06了

如何修复啊?

**Comment by dqylyln** [comment]
遇到同样问题，今天编译后发现smartdns 没了，查看安装包里面确定包含smartdns 就是菜单里没了，无法进入

**Comment by ixmu** [comment]
我今天也遇到了这个问题，不知道是什么原因，如何解决

**Comment by seaks** [comment]
> 我今天也遇到了这个问题，不知道是什么原因，如何解决

去下载18.06的luci 就好了

**Comment by reaiyaogun** [comment]
[https://github.com/kenzok8/openwrt-packages/commit/7a240640441404126f7231db97f1cbf1ee25a104](url)
k大已经把那个提交revert了。
