### ISSUE TITLE
单独编译

### ISSUE THREAD

**Issue by xaotag** [kenzok8/openwrt-packages#188]
你好~ 
请问怎么单独编译为一个 ipk

**Comment by metalbreeze** [comment]
你整体都编译完了。单个的ipk 自然有了

**Comment by kenzok8** [comment]
单独编译一个ipk 比如编译主题文件argon_new
一 、make menuconfig  勾选M

二、make package/luci-theme-argon_new/compile V=99

三、lede/bin/packages/x86_64/base 路径下文件
