### ISSUE TITLE
建议加入各类校园认证客户端

### ISSUE THREAD

**Issue by LittleRabbit8843** [kenzok8/openwrt-packages#19]
要是能加入一些校园认证的插件比如mentohust、minieap等就好了

**Comment by kenzok8** [comment]
我是做到尽量精简，而不是包罗万象，可能对于我来说，如果太多的软件就是成了个杂货铺了

B.Y_Jing <notifications@github.com> 于2020年6月1日周一 下午6:44写道：

**Comment by kenzok8** [comment]
放到一个新仓库地址了，自取吧
https://github.com/kenzok8/jell.git

**Comment by LittleRabbit8843** [comment]
非常感谢！

**Comment by kenzok8** [comment]
上次不是给你库的地址了么


B.Y_Jing <notifications@github.com> 于2020年7月17日周五 下午7:21写道：
