### ISSUE TITLE
smartdns更新了

### ISSUE THREAD

**Issue by siren202101** [kenzok8/openwrt-packages#195]
大佬，Smartdns官方已经更新了，这里的库还是1-3版本

**Comment by kenzok8** [comment]
哦，回头更新下

**Comment by realconnor** [comment]
> 哦，回头更新下

难道我理解错了？因为你21天前对smartdns Makefile的更新，PKG_SOURCE_VERSION并没有更新啊。
```
-PKG_MIRROR_HASH:=282bd4926fd33a949ba8a8a7f2a9eb83c09b540e88c782b2c739c6cb82b062a5
+PKG_MIRROR_HASH:=7f4a2d2b2295bd10b8c6fc64a42122a719bfff13761360e3f6b314e6e001910b
 PKG_SOURCE_VERSION:=11cf7b614c2ad42acf12cf4843daa1b67696763b
```
改HASH不是改了个寂寞？是不是应该把PKG_SOURCE_VERSION 改下？
PKG_SOURCE_VERSION - must be specified, the commit hash or SVN revision to check out.
