### ISSUE TITLE
AdGuardHome 页面显示错误

### ISSUE THREAD

**Issue by SterlingCarter** [kenzok8/openwrt-packages#20]
AdGuardHome页面下的"重定向"前面有个问号，如下图，希望大神可以修正一下！！ @kenzok8 

![image](https://user-images.githubusercontent.com/66172871/83654894-4e24f380-a5f0-11ea-9be2-27ad22c27cef.png)

**Comment by sxx1314** [comment]
这个问号是你设置的adg端口  有问题请用原项目的源码 这里版本号是12 是原项目下的beta版本  master版本是11

**Comment by SterlingCarter** [comment]
> 这个问号是你设置的adg端口 有问题请用原项目的源码 这里版本号是12 是原项目下的beta版本 master版本是11

什么意思？没明白
