### ISSUE TITLE
试图重现ADG compile问题的时候发现阿里云盘缺少依赖

### ISSUE THREAD

**Issue by Neurotoxin0** [kenzok8/openwrt-packages#202]
RT

Collecting package info: package/feeds/packages/udp-broadcast-relay-redux-openwr
Collecting package info: done
WARNING: Makefile 'package/openwrt-packages/luci-app-aliyundrive-webdav/Makefile' has a dependency on 'aliyundrive-webdav', which does not exist

feed里面是Lean默认的加上您主页上的两个：
src-git kenzo https://github.com/kenzok8/openwrt-packages
src-git small https://github.com/kenzok8/small

为了确保不是其他问题我删了旧的lede并且重新拉取了，还是少依赖

**Comment by Neurotoxin0** [comment]
目前加了个 src-git aliyundrive https://github.com/messense/aliyundrive-webdav/tree/main/openwrt/aliyundrive-webdav到feed来暂时避免

**Comment by kenzok8** [comment]
不好意思，git的时候少传了个aliyundrive-webdav ，所以导致编译失败
