### ISSUE TITLE
看了下大佬的插件库，发现少了个重要的没同步

### ISSUE THREAD

**Issue by OPnb** [kenzok8/openwrt-packages#208]
https://github.com/immortalwrt/openwrt-filebrowser
这个filebrowser超级好用，希望kenzok大佬以后同步搬运到您的这个packages里，谢谢了。爱您(￣y▽,￣)╭

**Comment by SterlingCarter** [comment]
kenzok大神的源码包里面是有你说的这个插件的，只是不在你说的这个packages里面,在这个packages里面：https://github.com/kenzok8/small-package
