### ISSUE TITLE
使用lede源码不能make menuconfig

### ISSUE THREAD

**Issue by angreman** [kenzok8/openwrt-packages#212]
使用lede源码不能make menuconfig。
如下报错代码：
1. tmp /.config-package.in: 65572: syntax error
2. tmp /.config-package.in:65571: invalid statement
3. tmp/ .config-package.in:65572: invalid statement
4. tmp/.config-package.in: 65573: invalid statement
5. tmp /.config-package.in:65574: invalid statement
6. make: ***[/hone/zengzhan/lede/include/toplevel.nk:134’menuconfig]错误1

翻了下.config-package.in中对应的代码行，发现是luci-app-ssr-plus的代码可能出现了问题，于是在执行./scripts/feeds install -a 之后把luci-app-ssr-plus的文件夹删除，即可正常执行make menuconfig。希望大佬看看是什么问题！

**Comment by joker357** [comment]
ssr那里出了错，那边已经改回来了，这边还没有更新，具体哪里可以看lean那边的

**Comment by angreman** [comment]
> ssr那里出了错，那边已经改回来了，这边还没有更新，具体哪里可以看lean那边的
