### ISSUE TITLE
luci-app-smartdns 服务里 界面不显示？

### ISSUE THREAD

**Issue by sxml** [kenzok8/openwrt-packages#216]
编译 luci-app-smartdns 服务里 界面不显示？

**Comment by claudeck** [comment]
我也碰到了这个问题。感觉应该是更新错了，原来的代码是来自于https://github.com/pymumu/luci-app-smartdns/tree/lede里面的lede分支，而不是master分支。现在变成了js版本了。。。

**Comment by WYC-2020** [comment]
@claudeck 你这个是不是太老了
