### ISSUE TITLE
/etc/init.d/AdGuardHome 脚本默认没有执行权限

### ISSUE THREAD

**Issue by RoninYuan-WY** [kenzok8/openwrt-packages#22]
编译完后，需要手动修改执行权限，否则AdGuardHome 无法启动。

**Comment by RoninYuan-WY** [comment]
分析后发现，/user/share/AdGuardHome/addhost.sh也没有执行权限。

**Comment by kenzok8** [comment]
此问题我早已发现了，简单粗暴的办法是
编译前用WinSCP去下载文件里 给adguardhome 与luci-app-adguardhome两个文件目录775权限，勾选下方的循环设定组、拥有者和权限

**Comment by RoninYuan-WY** [comment]
:-)

**Comment by tujj99** [comment]
> 此问题我早已发现了，简单粗暴的办法是
> 编译前用WinSCP去下载文件里 给adguardhome 与luci-app-adguardhome两个文件目录775权限，勾选下方的循环设定组、拥有者和权限

喜欢刨根问底的小白能问问，啥原因引起的？能否通过修改Makefile达到一劳永逸的目的？
