### ISSUE TITLE
filebrowser编译不成功

### ISSUE THREAD

**Issue by rq1025330** [kenzok8/openwrt-packages#228]
![image](https://user-images.githubusercontent.com/52870887/142809348-cc767e3e-551d-4138-80a9-5953ff963558.png)
大佬这是什么原因呢

**Comment by kenzok8** [comment]
是否选择了luci-app-advanced？高级设置里的filebrowser会编译冲突

**Comment by rq1025330** [comment]
![image](https://user-images.githubusercontent.com/52870887/142866451-4603f288-fafb-4295-8c52-7425d4c6c99b.png)
![image](https://user-images.githubusercontent.com/52870887/142866526-3ee304ce-e45f-41c2-a5af-9e43d405f1b4.png)
![image](https://user-images.githubusercontent.com/52870887/142866624-37d056cd-83cf-4064-9b37-b36fc1c0cd08.png)
没有。

**Comment by kenzok8** [comment]
![image](https://user-images.githubusercontent.com/39034242/142875055-959774de-d4e9-4b7c-90c1-4bb988a6957f.png)
我正常是不选择这个，你取消这个，试着编译下试试

**Comment by rq1025330** [comment]
我这会取消试试，我以前没取消也可以用

**Comment by rq1025330** [comment]
![image](https://user-images.githubusercontent.com/52870887/142964484-eb5420f8-c3ae-444f-8ba9-be4b12fcbfc6.png)
一样报错

**Comment by kenzok8** [comment]
make distclean
git pull && ./scripts/feeds update -a && ./scripts/feeds install -a && rm -rf ./tmp && make menuconfig
有时出错很玄学的，比如拉取dl文件时出错，怎么编译都过不了，我建议清除彻底，重新编译来一次

**Comment by rq1025330** [comment]
hao ,我再试试

**Comment by rq1025330** [comment]
![image](https://user-images.githubusercontent.com/52870887/143318966-c1f79cf7-8ca3-403c-87fa-1bf5e7748fea.png)
大佬依然不行

**Comment by rq1025330** [comment]
https://github.com/rq1025330/Actions-OP/blob/master/aarch64/.config
这是我本地编译的配置文件

**Comment by rq1025330** [comment]
![image](https://user-images.githubusercontent.com/52870887/143321228-ce573474-f1dc-495a-8f7d-c8a24a6144f6.png)
这个仓库的包和这个仓库
![image](https://user-images.githubusercontent.com/52870887/143321288-d40bec1b-f95b-4f8b-bf82-f79c6b376291.png)
一样不，用那个好

**Comment by rq1025330** [comment]
![image](https://user-images.githubusercontent.com/52870887/143321466-2265efae-8c96-456e-9cf1-8576ad1d27c3.png)

**Comment by zzhzy21** [comment]
luci-app-filebrowser  应该还有一个18.06分支，lede固件需要使用18.06分支
