### ISSUE TITLE
如何将仓库添加到openwrt的自定义软件源中

### ISSUE THREAD

**Issue by QTFIUE** [kenzok8/openwrt-packages#235]
![image](https://user-images.githubusercontent.com/95908233/146876728-f27dc38d-25ac-493f-8ab6-2e590551eb75.png)

**Comment by magi-Z** [comment]
软件源不是源码吧！

**Comment by kenzok8** [comment]
> ![image](https://user-images.githubusercontent.com/95908233/146876728-f27dc38d-25ac-493f-8ab6-2e590551eb75.png)

请参考
https://github.com/kenzok8/openwrt-packages/issues/295#issuecomment-1554385688

**Comment by QTFIUE** [comment]
感谢回复
