### ISSUE TITLE
可以单独订阅某几个插件吗？（找到相似的issues但是依然一头雾水）

### ISSUE THREAD

**Issue by weigeloveu** [kenzok8/openwrt-packages#240]
```
1、先去了解src-git的用法
2、单独拉取某个仓库里的源码 比如passwall
svn co https://github.com/kenzok8/openwrt-packages/trunk/luci-app-passwall
```
上边是k大给的解答，尝试了一下直接修改feeds文件发现并不能用。
尝试过
svn-src https://github.com/kenzok8/openwrt-packages/trunk/luci-app-passwall
也不行。
就是想实现像这样一样的效果，把某几个软件像这样订阅一下，然后随着./scripts/feeds update -a能自动拉取更新，不用每次手动去更新。还望大佬们不吝赐教
src-git kenzo https://github.com/kenzok8/openwrt-packages

**Comment by kenzok8** [comment]
svn co命令一般在命令行下运行的 脚本 bat等
feeds.conf.default里，只能用src-git smpackage https://github.com/kenzok8/small-package
其实你拉取这个镜像包裹，也不妨碍你编译啊
而且写入feeds.conf.default后， 运行
