### ISSUE TITLE
luci-app-argonne-config

### ISSUE THREAD

**Issue by cs-star** [kenzok8/openwrt-packages#242]
luci-app-argonne-config 不能自动更换图片了 8号编译的正常使用

**Comment by kenzok8** [comment]
另外的都正常吗？与argonne-config 无关，前两天修改argonne主题的缘故

**Comment by leesonaa** [comment]
老师您好，我编译出来的argonn主题连自定义图片都不能实现，是不是对图片有什么要求，如长宽比，命名之类的限制，恳请指导。

**Comment by cs-star** [comment]
@leesonaa https://github.com/kenzok8/small-package  luci-app-argon-config 这里正常

**Comment by leesonaa** [comment]
@cs-star 收到，感谢指导。我好像知道我自己错在哪了，一直以来feeds.conf.default文件都包含了两个源地址（https://github.com/kenzok8/openwrt-packages）和（https://github.com/kenzok8/small-package）。[捂脸]

**Comment by leesonaa** [comment]
好像更新源也不行哎。。是不是需要切换luci的版本呢。。
