### ISSUE TITLE
这个日志毫无意义

### ISSUE THREAD

**Issue by doumeki** [kenzok8/openwrt-packages#243]
5分钟就刷一次

Tue Jan 11 22:25:00 2022 cron.err crond[13155]: USER root pid 26193 cmd /usr/share/unblockneteasemusic/log_check.sh
Tue Jan 11 22:30:00 2022 cron.err crond[13155]: USER root pid 2515 cmd /usr/share/unblockneteasemusic/log_check.sh
Tue Jan 11 22:35:00 2022 cron.err crond[13155]: USER root pid 11288 cmd /usr/share/unblockneteasemusic/log_check.sh
Tue Jan 11 22:40:00 2022 cron.err crond[13155]: USER root pid 20015 cmd /usr/share/unblockneteasemusic/log_check.sh
Tue Jan 11 22:45:00 2022 cron.err crond[13155]: USER root pid 30095 cmd /usr/share/unblockneteasemusic/log_check.sh
Tue Jan 11 22:50:00 2022 cron.err crond[13155]: USER root pid 6398 cmd /usr/share/unblockneteasemusic/log_check.sh
Tue Jan 11 22:55:00 2022 cron.err crond[13155]: USER root pid 15209 cmd /usr/share/unblockneteasemusic/log_check.sh
Tue Jan 11 23:00:00 2022 cron.err crond[13155]: USER root pid 23920 cmd /usr/share/unblockneteasemusic/log_check.sh
Tue Jan 11 23:05:00 2022 cron.err crond[13155]: USER root pid 32642 cmd /usr/share/unblockneteasemusic/log_check.sh
Tue Jan 11 23:10:00 2022 cron.err crond[13155]: USER root pid 8933 cmd /usr/share/unblockneteasemusic/log_check.sh
Tue Jan 11 23:15:00 2022 cron.err crond[13155]: USER root pid 17729 cmd /usr/share/unblockneteasemusic/log_check.sh
Tue Jan 11 23:20:00 2022 cron.err crond[13155]: USER root pid 26446 cmd /usr/share/unblockneteasemusic/log_check.sh
Tue Jan 11 23:25:00 2022 cron.err crond[13155]: USER root pid 2769 cmd /usr/share/unblockneteasemusic/log_check.sh

**Comment by Nov-R** [comment]
我的openwrt也是这个问题，自己定义的定时任务无法启动，请教一下是什么原因啊 ？怎么解决？
