### ISSUE TITLE
passwall 问题

### ISSUE THREAD

**Issue by lzr1264823628** [kenzok8/openwrt-packages#25]
1. passwall 是不是不能和openclash混用
2. 使用trojan时,访问谷歌会出现隐私设置错误(证书问题)(我开了smart dns,我不知道是不是这个的问题)

**Comment by kenzok8** [comment]
什么叫混用？是指同时开启两个软件？若是同时开启肯定是不行的，容易dns错误

**Comment by lzr1264823628** [comment]
@kenzok8 我表达得不清楚,是我在固件编译的时候装了openclash和passwall,之后单独使用passwall,passwall 的dns解析不能了,其实我主要还是因为(我的固件的)passwall的trojan 有奇怪的问题,就是单独的google 访问不了,提示隐私错误(别劫持,证书错误什么的,开了smartdns的),要不然我还真不会去整openclash.

**Comment by kenzok8** [comment]
那没问题的，我的固件上就用了openclash +ssr+passwall，但是个人提议不要折腾dns 如果真的要玩dns的adg或者pi-hole等，建议虚拟机下玩

**Comment by lzr1264823628** [comment]
好的,谢谢
