### ISSUE TITLE
luci-app-store插件缺少依赖

### ISSUE THREAD

**Issue by ligehhh** [kenzok8/openwrt-packages#253]
WARNING: Makefile 'package/feeds/kenzok/luci-app-store/Makefile' has a dependency on 'luci-lib-ipkg', which does not exist

**Comment by ligehhh** [comment]
不知道是作者的依赖还是lede的，大佬看看能不能修复

**Comment by mumuou** [comment]
应该是这边的问题，最新代码也遇到了~~~

**Comment by xztxy** [comment]
同样遇到问题了。。

**Comment by WYC-2020** [comment]
改成luci-base

**Comment by ligehhh** [comment]
> > 改成 luci-base
> 
> 下，在哪里改

package/feeds/kenzok/luci-app-store/Makefile这个配置文件里面把那个依赖改成上面说的那个

**Comment by wow8szh** [comment]
> > > 改成 luci-base
> > 
> > 
> > 下，在哪里改
> 
> package/feeds/kenzok/luci-app-store/Makefile这个配置文件里面把那个依赖改成上面说的那个

打开了文件，还是不知道怎么改，你说详细一点吗？

**Comment by ligehhh** [comment]
![7X8$}SQ5Y__)4~16L@AA4E0](https://user-images.githubusercontent.com/61504899/156496181-5da9c8b0-400a-4c1c-991b-c2328a849738.png)
这样改

**Comment by ligehhh** [comment]
sed -i 's/luci-lib-ipkg/luci-base/g' package/feeds/kenzok/luci-app-store/Makefile   这个命令也可以

**Comment by xztxy** [comment]
> sed -i 's/luci-lib-ipkg/luci-base/g' package/feeds/kenzok/luci-app-store/Makefile 这个命令也可以

好的，感谢~！！
