### ISSUE TITLE
lede下编译，luci-app-store和shadowsocks-libev缺少依赖

### ISSUE THREAD

**Issue by hugcabbage** [kenzok8/openwrt-packages#254]
WARNING: Makefile 'package/openwrt-packages/luci-app-store/Makefile' has a dependency on 'luci-lib-ipkg', which does not exist
WARNING: Makefile 'package/small/shadowsocks-libev/Makefile' has a dependency on 'kmod-nft-tproxy', which does not exist

希望大佬修复下

**Comment by dalaoshi777** [comment]
我也看到了不过只是个警告，没理他
