### ISSUE TITLE
Packages to workaround usign SHA-512 bug!

### ISSUE THREAD

**Issue by Asminti** [kenzok8/openwrt-packages#260]
您好，请问一下，如下错误应该如何解决？是因为软件包勾选有冲突么？我尝试过make clean也仍旧如此。

make[3] -C target/linux install
 make[2] package/index
WARNING: Applying padding in /home/ubuntu/openwrt/bin/packages/x86_64/kenzo/Packages to workaround usign SHA-512 bug!
 make[2] json_overview_image_info
 make[2] checksum

**Comment by kenzok8** [comment]
不是云编译的话
make distclean #删除
重新来一次

**Comment by smdx** [comment]
同样遇到这个问题，云编译。请问需要重新编译吗？
