### ISSUE TITLE
还有就是大佬能添加[luci-app-amlogic](https://github.com/ophub/luci-app-amlogic)和 [luci-app-netdata_cn](https://github.com/sirpdboy/luci-app-netdata) 这两个插件吗？

### ISSUE THREAD

**Issue by KoWming** [kenzok8/openwrt-packages#263]
![屏幕截图 2022-03-24 190642](https://user-images.githubusercontent.com/96684377/159903689-b9f5a1ec-0087-4622-ba82-4d42fee1efd2.jpg)
拉取最新的源码编译后[argonneTheme v1.7.2](https://github.com/kenzok78/luci-theme-argonne)主题默认和上图不一样了，比较喜欢上图的样子和配色。

还有就是大佬能添加[luci-app-amlogic](https://github.com/ophub/luci-app-amlogic)和
[luci-app-netdata_cn](https://github.com/sirpdboy/luci-app-netdata)
这两个插件吗？我单独添加一直添加不进去

**Comment by kenzok8** [comment]
有人说丑，我就更改过来了，另外如果要很多插件，建议移步至https://github.com/kenzok8/small-package

**Comment by KoWming** [comment]
> 有人说丑，我就更改过来了，另外如果要很多插件，建议移步至https://github.com/kenzok8/small-package

是的，众口难调，我用small-package 试试，感谢大佬整理。

**Comment by ieasyseek** [comment]
> 有人说丑，我就更改过来了，另外如果要很多插件，建议移步至https://github.com/kenzok8/small-package

这个主题不丑啊，相当简洁好看。希望能给个链接。

**Comment by KoWming** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
