### ISSUE TITLE
adguardhome非常奇怪

### ISSUE THREAD

**Issue by warrenhoo** [kenzok8/openwrt-packages#265]
我原来用官方推荐的[rufengsuixing/luci-app-adguardhome](https://github.com/rufengsuixing/luci-app-adguardhome)编译的，此次用你的这个包来编译，新创建了一个用户来编译，全新开始，第一次选择了luci-app-adguardhome， 编译后，保留配置升级，（我原来的ag配置文件和工作目录都在/opt下），启动后luci界面进入”服务“——"adguardhome"，显示adguardhome已经启动，  工作目录和配置文件确实显示/opt下的相关文件，但点那个aguardhome web:3000按钮，竟然要重新配置adguard（我原来用rufengsuixing/luci-app-adguardhome编译的时候，每次升级系统都不用的，完整保留了我以前的配置）， 我重新配置创建了一个用户test，然后进入”服务“——"adguardhome"设置53端口取代dnsmasq，启动失败，提示有一个程序已经在运行，ssh发现/etc/ 有两个配置文件，一个是adguardhome.yml，里面的内容是是我刚点击aguardhome web:3000按钮创建的相关设置， 还有一个是AdGuardHome.yml， 是默认的模板文件（用户名是root），回到”服务“——"adguardhome"luci界面，把配置文件目录修改为/etc/AdGuardHome.yml，开关adguard， 再点aguardhome web:3000，它开始跳到AdGuardHome.yml这个文件的配置内容，用户名用户名是root，密码不清楚，修改密码后进入，配置确实是模板里的内容，比如设置了anti-AD过滤。 重启路由，再点击aguardhome web:3000，它又跳到adguardhome.yml这个文件的配置内容了，用户名是我刚创建的test，。开始排查原因，我查看了“系统”——“启动项”，发现竟然有两个adguard程序，一个是adguardhome，一个是AdGuardHome，问题就出在这了， 我把第一个adguardhome禁止开机启动，重启，第二个程序AdGuardHome正常，到了“服务”“adguardhome 的luci界面，点击aguardhome web:3000，是/etc/AdGuardHome.yml这个内容了，用户名是root，选择53端口取代dnsmasq启动成功。我再把工作目录和配置文件定位到我原来的/opt下，点击aguardhome web:3000， 用户回到了我升级系统前的admin 。重启，重复操作，点击 aguardhome web:3000，还是我升级系统前的配置， 终于正常。我仔细看了你的包里的源码，发现一个是adguardhome ，一个是luci-app-adguardhome，不知道是不是这个原因，系统创建了两个adguardhome程序，导致升级系统后无法正确配置。  我怀疑是不是不能保留配置升级， 虚拟机重新安装了一个openwrt，并没有用， 点击那个aguardhome web:3000，它就在/etc/AdGuardHome.yml 和adguardhome.yml 里配置的内容 切换，只有“系统”——“启动项” 禁止第一个adguardhome程序开机启动，才一切正常。

**Comment by kenzok8** [comment]
本来不想回复了，但是还是给小白解释下吧

**Comment by warrenhoo** [comment]
> 本来不想回复了，但是还是给小白解释下吧 adguardhome可以理解是内核文件 luci-app-adguardhome是图形操作插件而已

那为什么我用这个包编译出来”系统“ ——”启动项“会有两个adguardhome 程序呢，一个是adguardhome，一个是AdGuardHome， 但我用[rufengsuixing/luci-app-adguardhome](https://github.com/rufengsuixing/luci-app-adguardhome)编译的就只有一个启动项，很好奇为什么

**Comment by huxim** [comment]
确实有这个bug,要删掉全小写那个启动项,luci里的配置才会生效
![image](https://user-images.githubusercontent.com/2505801/161359935-a94af727-2d57-46f9-991a-2ddf5155854a.png)

**Comment by kenzok8** [comment]
[041f7f9](https://github.com/kenzok8/small-package/commit/041f7f9e5a34072470f4832cd1a8b02a5fb4d1ca)

**Comment by huxim** [comment]
> #265 ([kenzok8/small-package@9b920d1](https://github.com/kenzok8/small-package/commit/9b920d1056f7798490d5749575dd00e056591601))

只改配置文件恐怕不得行哦,还是有两个启动项,在luci里没法停止内核启动的进程

**Comment by kenzok8** [comment]
Makefile 51行 默认是/etc/adguardhome.yaml 小写
files/adguardhome.init 配置里是大写，除非都是大写，或者全部是小写，要不就产生不同的配置文件了

**Comment by huxim** [comment]
这个逻辑行不行: 如果选择了luci,就把内核那个启动项删掉,这样只选了内核和选了luci的都能正常工作?

**Comment by kenzok8** [comment]
把小写的删掉

**Comment by huxim** [comment]
我的意思是,编译脚本能不能自动干这件事情

**Comment by Huadao1108** [comment]
貌似一个是Adg的，另一个是luci-app-adg的。我看makefile一个是大写，一个是小写。会不会是这个问题。

**Comment by Huadao1108** [comment]
> Makefile 50行 默认是/etc/adguardhome.yaml 小写 files/adguardhome.init 配置里是大写，除非都是大写，或者全部是小写，要不就产生不同的配置文件了

**Comment by Huadao1108** [comment]
> Makefile 50行 默认是/etc/adguardhome.yaml 小写 files/adguardhome.init 配置里是大写，除非都是大写，或者全部是小写，要不就产生不同的配置文件了
