### ISSUE TITLE
这怎么解决

### ISSUE THREAD

**Issue by mmeiwenlong** [kenzok8/openwrt-packages#272]
![QQ截图20220413221838](https://user-images.githubusercontent.com/44661424/163201498-4d176ca0-b5d7-4309-ac5a-135165680edd.png)

**Comment by kenzok8** [comment]
rm -rf ./feeds && ./scripts/feeds update -a && ./scripts/feeds install -a && rm -rf ./tmp && make menuconfig

**Comment by mmeiwenlong** [comment]
> rm -rf ./feeds && ./scripts/feeds update -a && ./scripts/feeds install -a && rm -rf ./tmp && make menuconfig



谢谢
