### ISSUE TITLE
luci-app-passwall 缺少dns2tcp依赖

### ISSUE THREAD

**Issue by ligehhh** [kenzok8/openwrt-packages#287]
WARNING: Makefile 'package/feeds/kenzok/luci-app-passwall/Makefile' has a dependency on 'dns2tcp', which does not exist
github好像有  https://github.com/pexcn/openwrt-dns2tcp   ，不知道能不能用
这个好像是个2016年的旧依赖？

**Comment by kenzok8** [comment]
small里已添加
