### ISSUE TITLE
adguardhome 编译进去之后 关闭不了，一直在运行状态

### ISSUE THREAD

**Issue by Baojun-Chen** [kenzok8/openwrt-packages#288]
X86 的架构
![ad](https://user-images.githubusercontent.com/56340302/168224831-e43a1642-af42-4b03-83b0-08015525a759.png)
![ad2](https://user-images.githubusercontent.com/56340302/168224844-016b83e9-8521-44e3-a3df-d081bf2eadd4.png)

**Comment by kenzok8** [comment]
系统--启动项里关闭试试看呢

**Comment by Baojun-Chen** [comment]
> 系统--启动项里关闭试试看呢

可以了，这是什么操作，我头麻了！！！

谢谢大佬。
