### ISSUE TITLE
AdGuard Home 一直在运行中，无法关闭

### ISSUE THREAD

**Issue by Baojun-Chen** [kenzok8/openwrt-packages#289]
查到了一个问题，原因是 /etc/init.d里面有两个启动文件一个大写一个小写的。删除掉小写的那个 启动文件就正常了。

但是为什么会编译出来两个呢?

![image](https://user-images.githubusercontent.com/56340302/168429005-002dcce2-9f78-4123-bc23-8c43cddd6f69.png)

![image](https://user-images.githubusercontent.com/56340302/168428966-6e2a1569-e6e8-4f03-aa18-875e6efd87e0.png)

**Comment by kenzok8** [comment]
是Lean源码吗？
因为L大源码net里有AdGuard,所以编译出来etc/init路径下会两个

**Comment by Baojun-Chen** [comment]
> 是Lean源码吗？ 因为L大源码net里有AdGuard,所以编译出来etc/init路径下会两个

是有个诶，还取消不了  大佬这种情况该怎么办啊
![image](https://user-images.githubusercontent.com/56340302/168460569-ea0015ad-5b69-4412-87ec-7d55400ef4ba.png)

**Comment by ligehhh** [comment]
后台有进程kill掉就没有了

**Comment by zombieht** [comment]
我也遇到这个问题，自带的在config里去掉会报错，没要手动kill好麻烦

**Comment by kenzok8** [comment]
我说Lean的源码里有，在net下要删除源码自带的adguardhome
比如 命令  rm -rf feeds/packages/net/adguardhome

**Comment by mcusee** [comment]
> 除源码自带的adguardhome
> 比如 命令 rm -rf feeds/packages/

删除这个报错

**Comment by mcusee** [comment]
> > 除源码自带的adguardhome
> > 比如 命令 rm -rf feeds/packages/
> 
> 删除这个报错
WARNING: Makefile 'package/feeds/kenzo/luci-app-adguardhome/Makefile' has a dependency on 'adguardhome', which does not exist

**Comment by mcusee** [comment]
> > > 除源码自带的adguardhome
> > > 比如 命令 rm -rf feeds/packages/
> > 
> > 
> > 删除这个报错
> > WARNING: Makefile 'package/feeds/kenzo/luci-app-adguardhome/Makefile' has a dependency on 'adguardhome', which does not exist

make[3]: *** [Makefile:87: /home/eason/lede/build_dir/target-x86_64_musl/adguardhome-0.107.51/.built] Error 1
make[3]: Leaving directory '/home/eason/lede/feeds/kenzo/adguardhome'
time: package/feeds/kenzo/adguardhome/compile#2.72#4.73#23.79
    ERROR: package/feeds/kenzo/adguardhome failed to build.
make[2]: *** [package/Makefile:116: package/feeds/kenzo/adguardhome/compile] Error 1
make[2]: Leaving directory '/home/eason/lede'
make[1]: *** [package/Makefile:110: /home/eason/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/eason/lede'
make: *** [/home/eason/lede/include/toplevel.mk:231：world] 错误 2
