### ISSUE TITLE
passwall插件出现告警

### ISSUE THREAD

**Issue by huahua315148** [kenzok8/openwrt-packages#292]
WARNING: Makefile 'package/feeds/kenzo/luci-app-passwall/Makefile' has a dependency on 'brook', which does not exist
WARNING: Makefile 'package/feeds/kenzo/luci-app-passwall/Makefile' has a dependency on 'hysteria', which does not exist
WARNING: Makefile 'package/feeds/kenzo/luci-app-passwall2/Makefile' has a dependency on 'brook', which does not exist
WARNING: Makefile 'package/feeds/kenzo/luci-app-passwall2/Makefile' has a dependency on 'hysteria', which does not exist

**Comment by kenzok8** [comment]
重新拉取下，丢失插件了
