### ISSUE TITLE
 make[2] -C feeds/small/trojan download     ERROR: package/feeds/small/hysteria failed to build.

### ISSUE THREAD

**Issue by lisonglin980** [kenzok8/openwrt-packages#294]
![image](https://user-images.githubusercontent.com/68982838/169689370-fcb28a7a-2f43-4586-abee-4b187552872e.png)

**Comment by lisonglin980** [comment]
大佬 是不是又有什么挂了

**Comment by lisonglin980** [comment]
![image](https://user-images.githubusercontent.com/68982838/169689491-770030d2-f3ea-4a91-9e15-9fb99714f622.png)

**Comment by wggglggg** [comment]
passwall里面那个hysteria组件吧，上上油管，这个东西不是必要的组件，不用钩

**Comment by 6bf3803cb456** [comment]
看日志，有没有golang或者其他依赖下载失败了。

**Comment by justin-himself** [comment]
<img width="834" alt="image" src="https://user-images.githubusercontent.com/73123028/185726761-a968c2cf-6f73-416c-8067-7a3549062628.png">
