### ISSUE TITLE
Adguard Home的makefile有问题

### ISSUE THREAD

**Issue by hyy-666** [kenzok8/openwrt-packages#30]
按照库里的makefile下载的AdguardHome为V0.102.1的版本
而官方的最新版本为V0.102.0，遂将makefile修改为
PKG_VERSION:=v0.102
PKG_RELEASE:=0

**Comment by kenzok8** [comment]
没啥问题的

**Comment by hyy-666** [comment]
编译时会下载V0.102.0.1的Adguardhome，您可以清空一下dl库再试试看

**Comment by kenzok8** [comment]
https://github.com/Lienol/openwrt/blob/dev-19.07/package/diy/adguardhome/Makefile

**Comment by hyy-666** [comment]
![image](https://user-images.githubusercontent.com/57535444/85319445-170d7800-b4f4-11ea-9b68-9d571c91c557.png)
![image](https://user-images.githubusercontent.com/57535444/85319472-2260a380-b4f4-11ea-80bb-96091aaa0d5e.png)
上面是您的Makefile的拉取地址，下面是lienol的

**Comment by kenzok8** [comment]
谢谢指正！
