### ISSUE TITLE
ShadowsocksR Plus+ 编译出来后 xray 无法运行（小米3G）

### ISSUE THREAD

**Issue by sonytxl** [kenzok8/openwrt-packages#304]
ShadowsocksR Plus+ 编译出来后 xray 无法运行（小米3G）
今天编译时候ssplus+出现了xray的选项，就编译进去，结果刷进去路由器，xray无法运行，在xray下的trojan,v2ray,等等都无法运行，请问各位有没有遇到这个情况，谢谢。。。

**Comment by Kalansas** [comment]
小米3G性能不够用，不要把xray编进去
