### ISSUE TITLE
编译最新的mosdns报错

### ISSUE THREAD

**Issue by jinjin327** [kenzok8/openwrt-packages#308]
WARNING: Makefile 'package/feeds/small8/luci-app-mosdns/Makefile' has a dependency on 'mosdns_neo', which does not exist

**Comment by ligehhh** [comment]
缺依赖了

**Comment by ligehhh** [comment]
https://github.com/xcf13363175/openwrt-mos/blob/master/mosdns_neo/Makefile   这个应该是依赖包 大佬添加一下

**Comment by kenzok8** [comment]
修复了

**Comment by aiemassfiria** [comment]
Still error

**Comment by jinjin327** [comment]
> 修复了

还是提示缺少依赖mosdns_neo

**Comment by zhangguanzhang** [comment]
还是提示缺少依赖mosdns_neo, +1

**Comment by kenzok8** [comment]
rm -rf feeds/packages/net/mosdns

**Comment by zhangguanzhang** [comment]
> rm -rf feeds/packages/net/mosdns
> 
> 把L大的源码自带的mosdns删除

不行，可以看 
https://github.com/zhangguanzhang/Actions-OpenWrt/runs/7062937300?check_suite_focus=true#step:9:458
https://github.com/zhangguanzhang/Actions-OpenWrt/runs/7062937300?check_suite_focus=true#step:15:77

**Comment by WYC-2020** [comment]
这玩意吧那个mosdns_neo改成mosdns

**Comment by lisonglin980** [comment]
BuildPackage 变量
PKG_*定义了软件包相关的一些基本信息，如下所示：
PKG_NAME -包的名称,可以通过menuconfig和ipkg看到。 不要使用下划线。

mosdns_neo应该改成mosdns-neo吧

**Comment by lisonglin980** [comment]
> rm -rf feeds/packages/net/mosdns

rm了一样报错找不到依赖mosdns_neo

**Comment by WYC-2020** [comment]
> BuildPackage 变量 PKG_*定义了软件包相关的一些基本信息，如下所示： PKG_NAME -包的名称,可以通过menuconfig和ipkg看到。 不要使用下划线。
> 
> mosdns_neo应该改成mosdns-neo吧

看上游嘛，都给你说了吧那个依赖去掉neo，这就是每个人定义的包名不同而已，l大不带neo，这个插件的作者也去掉neo了，这库应该是作者以前自己私自明名的而已

**Comment by lisonglin980** [comment]
> > BuildPackage 变量 PKG_*定义了软件包相关的一些基本信息，如下所示： PKG_NAME -包的名称,可以通过menuconfig和ipkg看到。 不要使用下划线。
> > mosdns_neo应该改成mosdns-neo吧
> 
> 看上游嘛，都给你说了吧那个依赖去掉neo，这就是每个人定义的包名不同而已，l大不带neo，这个插件的作者也去掉neo了，这库应该是作者以前自己私自明名的而已

直接把\feeds\kenzo\luci-app-mosdns\Makefile里面的LUCI_DEPENDS:=+mosdns_neo这里删掉_neo吗

**Comment by zhangguanzhang** [comment]
> rm -rf feeds/packages/net/mosdns
> 
> 把L大的源码自带的mosdns删除

https://github.com/kenzok8/openwrt-packages/blob/9b57ea758278ad94326c088725e06f1baa3eade2/luci-app-mosdns/Makefile#L9 这里你没改

**Comment by lisonglin980** [comment]
> > rm -rf feeds/packages/net/mosdns
> > 把L大的源码自带的mosdns删除
> 
> https://github.com/kenzok8/openwrt-packages/blob/9b57ea758278ad94326c088725e06f1baa3eade2/luci-app-mosdns/Makefile#L9
> 
> 这里你没改

我改的就是这个地方呀，只有这一处吗

**Comment by zhangguanzhang** [comment]
> > > rm -rf feeds/packages/net/mosdns
> > > 把L大的源码自带的mosdns删除
> > 
> > 
> > https://github.com/kenzok8/openwrt-packages/blob/9b57ea758278ad94326c088725e06f1baa3eade2/luci-app-mosdns/Makefile#L9
> > 
> > 这里你没改
> 
> 我改的就是这个地方呀，只有这一处吗
```
find -type f -name Makefile -exec grep -l mosdns_neo {} \;
```
命令查找下看看

**Comment by wx1wxc** [comment]
` * pkg_hash_check_unresolved: cannot find dependency mosdns-neo for luci-app-mosdns
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-mosdns found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-mosdns.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-mosdns-zh-cn:
 * 	mosdns-neo
 * opkg_install_cmd: Cannot install package luci-i18n-mosdns-zh-cn.
make[2]: *** [package/Makefile:70: package/install] Error 255`


今天编译还是出错

**Comment by lee29** [comment]
> 

云编译yml可以这样改
`    - name: 去除重复应用包
      run: |
         cd openwrt

         sudo rm -rf ./feeds/packages/net/mosdns && cp -rf ./feeds/kenzo/mosdns ./feeds/packages/net/mosdns
         sed -i 's/mosdns_neo/mosdns/g' ./feeds/kenzo/luci-app-mosdns/Makefile
         sed -i 's/mosdns_neo/mosdns/g' ./feeds/kenzo/mosdns/Makefile
         sed -i 's/mosdns_neo/mosdns/g' ./feeds/packages/net/mosdns/Makefile
 
         
               
    - name: 安装 feeds 应用包
      run: cd openwrt && ./scripts/feeds install -a`

**Comment by jonwhoo** [comment]
这样处理不报错了，编译一下看看

**Comment by zhangguanzhang** [comment]
@kenzok8 老大为啥不改下更新下

**Comment by wangwei123321** [comment]
问题解决了么，怎么解决啊

**Comment by kenzok8** [comment]
抱歉，最近搬家，所以耽搁了修复了
