### ISSUE TITLE
recursive dependency detected!

### ISSUE THREAD

**Issue by msdos03** [kenzok8/openwrt-packages#315]
tmp/.config-package.in:60949:error: recursive dependency detected!
tmp/.config-package.in:60949:	symbol PACKAGE_luci-app-mosdns depends on PACKAGE_mosdns
tmp/.config-package.in:105136:	symbol PACKAGE_mosdns is selected by PACKAGE_luci-app-mosdns
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

**Comment by Falld0wn18** [comment]
执行 make menuconfig 时出现的吧？最终编译貌似没什么问题。
