### ISSUE TITLE
naiveproxy Failed To build with binutils 2.39 

### ISSUE THREAD

**Issue by kontorol** [kenzok8/openwrt-packages#323]
make[3] -C feeds/kenzo/naiveproxy compile
    ERROR: package/devel/binutils failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 1

**Comment by ligehhh** [comment]
跑一线程看
