### ISSUE TITLE
用OPENWRT官方源码编译没有UnblockNeteaseMusic的选项

### ISSUE THREAD

**Issue by haruhitamako** [kenzok8/openwrt-packages#329]
openwrt的feed包里能看见UnblockNeteaseMusic和luci-app-unblockneteasemusic，但是在make menuconfig中看不见相关的选项，要是用lean的lede源编译就能看见。

**Comment by haruhitamako** [comment]
打搅了，问题找到了，openwrt官方源已经在新内核移除fpu支持了

remove KERNEL_MIPS_FPU_EMULATOR after kernel 4.14 and 4.14 are gone

**Comment by Zephor5** [comment]
有什么解决方案吗
