### ISSUE TITLE
which does not exist configuration written to .config

### ISSUE THREAD

**Issue by seaks** [kenzok8/openwrt-packages#331]
WARNING: Makefile 'package/feeds/kenzo/luci-app-bypass/Makefile' has a dependency on 'lua-neturl', which does not exist
WARNING: Makefile 'package/feeds/kenzo/luci-app-filebrowser/Makefile' has a dependency on 'filebrowser', which does not exist
WARNING: Makefile 'package/feeds/kenzo/luci-app-ssr-plus/Makefile' has a dependency on 'lua-neturl', which does not exist
configuration written to .config

**Comment by Ginua8292** [comment]
昨天还好好的!今天就少了依赖！

**Comment by X-Firefly** [comment]
同样提示依赖错误

**Comment by seaks** [comment]
> 昨天还好好的!今天就少了依赖！



> 同样提示依赖错误

clean后我拉这个库 就好了 sed -i '$a src-git openwrtpasswall https://github.com/xiaorouji/openwrt-passwall' feeds.conf.default

**Comment by Racon94** [comment]
我昨天提过，应该是kenzo误删了吧？我是自己fork了一个库，自己加进去了。也可以像楼上说的，加别人的feeds库
https://github.com/kenzok8/openwrt-packages/issues/322#issue-1338104317

**Comment by Kisoul** [comment]
我也出现了这个问题
