### ISSUE TITLE
今天编译报错

### ISSUE THREAD

**Issue by ronnie9211** [kenzok8/openwrt-packages#337]
WARNING: Makefile 'package/feeds/kenzo/luci-app-bypass/Makefile' has a dependency on 'luci-lib-ipkg', which does not exist

**Comment by neckyaan** [comment]
同上

**Comment by kenzok8** [comment]
luci-app-bypass/Makefile 编辑25行 luci-lib-ipkg 删除这行

**Comment by anjue39** [comment]
> luci-app-bypass/Makefile 编辑25行 luci-lib-ipkg 删除这行

请更新一下

**Comment by anjue39** [comment]
收到，最好直接从你库里修复了，如果它是bug



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: smmya ***@***.***&gt;
发送时间: 2022年10月7日 11:57
收件人: kenzok8/openwrt-packages ***@***.***&gt;
抄送: anjue39 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [kenzok8/openwrt-packages] 今天编译报错 (Issue #337)





  
luci-app-bypass/Makefile 编辑25行 luci-lib-ipkg 删除这行
 将luci-lib-ipkg改为luci-base也可以
