### ISSUE TITLE
大佬们帮忙看一下这2个报错

### ISSUE THREAD

**Issue by johngui** [kenzok8/openwrt-packages#339]
make[3]: *** [Makefile:56: /home/appgess/openwrt/build_dir/target-arm_cortex-a9_musl_eabi/hysteria-1.2.1/.built] Error 2
make[3]: Leaving directory '/home/appgess/openwrt/feeds/small8/hysteria'
time: package/feeds/small8/hysteria/compile#0.60#0.99#1.24
    ERROR: package/feeds/small8/hysteria failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small8/hysteria/compile] Error 1
make[2]: Leaving directory '/home/appgess/openwrt'
make[1]: *** [package/Makefile:110: /home/appgess/openwrt/staging_dir/target-arm_cortex-a9_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/appgess/openwrt'
make: *** [/home/appgess/openwrt/include/toplevel.mk:230: world] Error 2

**Comment by kenzok8** [comment]
hysteria  failed to build,看报错是没下载成功
