### ISSUE TITLE
vssr缺少lua-maxminddb依赖

### ISSUE THREAD

**Issue by cerellean** [kenzok8/openwrt-packages#348]
如题，编译报错！

**Comment by HollyMadCow** [comment]
自己去git一个
cd lede/package/lean/  

git clone https://github.com/jerrykuku/lua-maxminddb.git

**Comment by cerellean** [comment]
> 自己去git一个 cd lede/package/lean/
> 
> git clone https://github.com/jerrykuku/lua-maxminddb.git

已经手动git了一个

**Comment by kenzok8** [comment]
上有bypass仓库丢失，已补上
