### ISSUE TITLE
luci-app-unblockneteasemusic编译后不显示

### ISSUE THREAD

**Issue by Pan5094** [kenzok8/openwrt-packages#355]
luci-app-unblockneteasemusic编译后不显示

**Comment by mulder125** [comment]
确实有这个问题，我已找到原因。
是因为拉到3.x版本的，3.x版本是for js。
正确要用2.x版本的(master)
![image](https://user-images.githubusercontent.com/32414985/215922594-2aa4dc13-5f6c-48bb-a17a-a823b9a01df0.png)

**Comment by kenzok8** [comment]
> 确实有这个问题，我已找到原因。 是因为拉到3.x版本的，3.x版本是for js。 正确要用2.x版本的(master) ![image](https://user-images.githubusercontent.com/32414985/215922594-2aa4dc13-5f6c-48bb-a17a-a823b9a01df0.png)

嗯，没看仔细，谢谢

**Comment by mulder125** [comment]
更新后实测OK！

**Comment by kenzok8** [comment]
> [f98914b](https://github.com/kenzok8/openwrt-packages/commit/f98914b6d5c10ac81072b91ddf6d06586af04fbb) 更新后实测无问题！

OK
