### ISSUE TITLE
新年好，可以更新一下smartdns吗？

### ISSUE THREAD

**Issue by smdx** [kenzok8/openwrt-packages#358]
新年好，可以更新一下smartdns吗？官方最近更新很频繁增加功能、修复不少问题。谢谢

**Comment by kenzok8** [comment]
新年好
https://github.com/pymumu/smartdns/releases/tag/Release40
难道有更新的吗？

**Comment by kenzok8** [comment]
默认我是拉取eleases/tag/下的最新发布

**Comment by smdx** [comment]
明白了，那没什么问题了。我关闭issue了
