### ISSUE TITLE
nanopi-r4s 最近几个月的更新变为13MB左右，刷入后无法进入系统了

### ISSUE THREAD

**Issue by rainoooooo** [kenzok8/openwrt-packages#359]
连续几月的R4s固件已经无法使用了，不知道问题在哪里？大佬留意看看？？

**Comment by kenzok8** [comment]
收到，这两天我有空看看

**Comment by kenzok8** [comment]
我没有R4s机器，重新编译了，有空你去测试一下看看，谢

**Comment by rainoooooo** [comment]
测试了，还是无法连接，直接连网线不显示路由器地址。

发自我的 iPhone

在 2023年2月1日，15:10，有種 ***@***.***> 写道：

﻿

我没有R4s机器，重新编译了，有空你去测试一下看看，谢
