### ISSUE TITLE
luci-app-passwall 5小时前更新存在错误，更新节点订阅出错！

### ISSUE THREAD

**Issue by gswangmd-gssi** [kenzok8/openwrt-packages#36]

**Comment by kenzok8** [comment]
Lienol大神应该已经修复了！已经更新

**Comment by gswangmd-gssi** [comment]
刚试过了，未修复。

有種 <notifications@github.com> 于2020年7月11日周六 上午8:14写道：

**Comment by tjlive** [comment]
昨晚半夜又有更新。

**Comment by gswangmd-gssi** [comment]
刚才编译测试了一下。你需要再更新一下源码，lienol的已经没问题，但你的源码依然有问题！发自我的华为手机-------- 原始邮件 --------发件人： tjlive <notifications@github.com>日期： 2020年7月12日周日 下午1:33收件人： kenzok8/openwrt-packages <openwrt-packages@noreply.github.com>抄送： gswangmd-gssi <gssiwmd@gmail.com>, Author <author@noreply.github.com>主    题： Re: [kenzok8/openwrt-packages] luci-app-passwall 5小时前更新存在错误，更新节点订阅出错！ (#36)

昨晚半夜又有更新。
