### ISSUE TITLE
error in first code

### ISSUE THREAD

**Issue by mmpma** [kenzok8/openwrt-packages#362]
why i get this error?
root@X-WRT:~# sed -i '$a src-git small https://github.com/kenzok8/small' feeds.conf.default
sed: feeds.conf.default: No such file or director

there isn't any toturial for install on xwrt?

**Comment by HollyMadCow** [comment]
edit file feeds.conf.default
add   

src-git small https://github.com/kenzok8/small

to the last line 

then run ./scripts/feeds update -a && ./scripts/feeds install -a

**Comment by mmpma** [comment]
> edit file feeds.conf.default add
> 
> src-git small https://github.com/kenzok8/small
> 
> to the last line
> 
> then run ./scripts/feeds update -a && ./scripts/feeds install -a

where is the location of  file feeds.conf.default

**Comment by kenzok8** [comment]
is this repo？
https://github.com/x-wrt/x-wrt
![image](https://user-images.githubusercontent.com/39034242/215502707-3d9e9ea3-466f-4d51-8de5-0293a9cb501b.png)

**Comment by kenzok8** [comment]
Compile is not a root user, “feeds.conf.default” is in the wrt directory
