### ISSUE TITLE
alist编译错误

### ISSUE THREAD

**Issue by vinwinchen** [kenzok8/openwrt-packages#363]
github.com/alist-org/alist/v3/pkg/gowebdav/cmd/gowebdav
github.com/alist-org/alist/v3/internal/search
github.com/aws/aws-sdk-go/service/s3/s3manager
github.com/alist-org/alist/v3/server/handles
github.com/alist-org/alist/v3/drivers/123
github.com/alist-org/alist/v3/drivers/mediatrack
github.com/alist-org/alist/v3/drivers/pikpak
github.com/alist-org/alist/v3/drivers/s3
github.com/alist-org/alist/v3/drivers/thunder
github.com/alist-org/alist/v3/server
github.com/alist-org/alist/v3/drivers
github.com/jackc/pgx/v5
github.com/jackc/pgx/v5/stdlib
gorm.io/driver/postgres
gorm.io/driver/sqlite
github.com/alist-org/alist/v3/internal/bootstrap
github.com/alist-org/alist/v3/cmd
github.com/alist-org/alist/v3

make[3]: *** [Makefile:102: /home/make/lede/build_dir/target-x86_64_musl/alist-3.9.2/.built] Error 2
make[3]: Leaving directory '/home/make/lede/feeds/kenzo/alist'
time: package/feeds/kenzo/alist/compile#81.65#15.58#57.57
    ERROR: package/feeds/kenzo/alist failed to build.
make[2]: *** [package/Makefile:116: package/feeds/kenzo/alist/compile] Error 1
make[2]: Leaving directory '/home/make/lede'
make[1]: *** [package/Makefile:110: /home/make/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/make/lede'
make: *** [/home/make/lede/include/toplevel.mk:231: world] Error 2

**Comment by jinjin327** [comment]
遇到一样的问题

**Comment by ThingsWhy** [comment]
我这里也是，我单独编译luci-app-alist的时候第一行出来了关于mosdns的依赖信息![image](https://user-images.githubusercontent.com/37958754/216053339-67c960bc-db26-44eb-ab49-a72b040135ab.png)

**Comment by vinwinchen** [comment]
``Building targets
github.com/winfsp/cgofuse/fuse
# github.com/winfsp/cgofuse/fuse
../../../../../dl/go-mod-cache/github.com/winfsp/cgofuse@v1.5.0/fuse/host_cgo.go:116:10: fatal error: fuse.h: No such file or directory
  116 | #include <fuse.h>
      |          ^~~~~~~~
compilation terminated.

make[3]: *** [Makefile:102: /home/make/lede/build_dir/target-x86_64_musl/alist-3.9.2/.built] Error 2
make[3]: Leaving directory '/home/make/lede/feeds/kenzo/alist'
time: package/feeds/kenzo/alist/compile#1.83#0.63#1.33
    ERROR: package/feeds/kenzo/alist failed to build.
make[2]: *** [package/Makefile:116: package/feeds/kenzo/alist/compile] Error 1
make[2]: Leaving directory '/home/make/lede'
make[1]: *** [package/Makefile:110: /home/make/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/make/lede'
make: *** [/home/make/lede/include/toplevel.mk:231: world] Error 2

**Comment by xinaz** [comment]
碰到一样的问题
Building targets
github.com/winfsp/cgofuse/fuse
# github.com/winfsp/cgofuse/fuse
../../../../../dl/go-mod-cache/github.com/winfsp/cgofuse@v1.5.0/fuse/host_cgo.go:116:10: fatal error: fuse.h: No such file or directory
  116 | #include <fuse.h>
      |          ^~~~~~~~
compilation terminated.

make[3]: *** [Makefile:102: /home/xinaz/project/lede/build_dir/target-arm_cortex-a9_musl_eabi/alist-3.10.1/.built] Error 2
make[3]: Leaving directory '/home/xinaz/project/lede/feeds/kenzok/alist'
time: package/feeds/kenzok/alist/compile#4.99#1.76#2.85
    ERROR: package/feeds/kenzok/alist failed to build.
make[2]: *** [package/Makefile:116: package/feeds/kenzok/alist/compile] Error 1
make[2]: Leaving directory '/home/xinaz/project/lede'
make[1]: *** [package/Makefile:110: /home/xinaz/project/lede/staging_dir/target-arm_cortex-a9_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/xinaz/project/lede'
make: *** [/home/xinaz/project/lede/include/toplevel.mk:231: world] Error 2
[xinaz@localhost lede]$ make menuconfig
configuration written to .config

**Comment by dudulongg** [comment]
我也是同样的问题，等待作者修正吧

**Comment by kenzok8** [comment]
参考作者的提示
更新 golang 19.x

rm -rf feeds/packages/lang/golang
svn export https://github.com/sbwml/packages_lang_golang/branches/19.x feeds/packages/lang/golang

**Comment by ThingsWhy** [comment]
确实还是云编译失败了

**Comment by fseteen** [comment]
> 参考作者的提示 更新 golang 19.x
> 
> rm -rf feeds/packages/lang/golang svn export https://github.com/sbwml/packages_lang_golang/branches/19.x feeds/packages/lang/golang

编译成功！

**Comment by dudulongg** [comment]
我重装Ubuntu从新配置menuconfig就好了

**Comment by kenzok8** [comment]
> 删掉lede目录都不行，重装Ubuntu从新配置menuconfig就好了

精神可嘉，折腾不止

**Comment by kvmcore** [comment]
> 参考作者的提示 更新 golang 19.x
> 
> rm -rf feeds/packages/lang/golang svn export https://github.com/sbwml/packages_lang_golang/branches/19.x feeds/packages/lang/golang

装上fuse开发包，问题已解决。

ubuntu/debian:
sudo apt install libfuse-dev

CentOS:
sudo yum install fuse-devel

**Comment by vinwinchen** [comment]
> > 参考作者的提示 更新 golang 19.x
> > rm -rf feeds/packages/lang/golang svn export https://github.com/sbwml/packages_lang_golang/branches/19.x feeds/packages/lang/golang
> 
> 装上fuse开发包，问题已解决。
> 
> ubuntu/debian: sudo apt install libfuse-dev
> 
> CentOS: sudo yum install fuse-devel

这个方法最好用

**Comment by michealhansun** [comment]
> > 参考作者的提示 更新 golang 19.x
> > rm -rf feeds/packages/lang/golang svn export https://github.com/sbwml/packages_lang_golang/branches/19.x feeds/packages/lang/golang
> 
> 装上fuse开发包，问题已解决。
> 
> ubuntu/debian: sudo apt install libfuse-dev
> 
> CentOS: sudo yum install fuse-devel

你好，请问github actions 云编译时如何添加命令安装

**Comment by ThingsWhy** [comment]
> > > 参考作者的提示 更新 golang 19.x
> > > rm -rf feeds/packages/lang/golang svn export https://github.com/sbwml/packages_lang_golang/branches/19.x feeds/packages/lang/golang
> > 
> > 
> > 装上fuse开发包，问题已解决。
> > ubuntu/debian: sudo apt install libfuse-dev
> > CentOS: sudo yum install fuse-devel
> 
> 你好，请问github actions 云编译时如何添加命令安装

类似这样
![image](https://github.com/kenzok8/openwrt-packages/assets/37958754/dbbcbcca-b633-42f3-a9c4-8c947c22c72b)
不过我现在似乎不需要了，用的那个分支已经更新了依赖了
