### ISSUE TITLE
naiveproxy编译报错

### ISSUE THREAD

**Issue by fuwa2019** [kenzok8/openwrt-packages#365]
![photo_2023-01-31_10-47-53](https://user-images.githubusercontent.com/56064365/215740700-78527dec-a0c4-4488-b565-5a1dc14686e4.jpg)

**Comment by CJLUGaoXinyu** [comment]
同报错

**Comment by mulder125** [comment]
1/31晚上的update已经fix
[98b2972](https://github.com/kenzok8/openwrt-packages/commit/98b2972b754adc4fbdca7b374de591f7003baa05)
