### ISSUE TITLE
naiveproxy 编译错误

### ISSUE THREAD

**Issue by keivenliao** [kenzok8/openwrt-packages#366]
![image](https://user-images.githubusercontent.com/12838693/216001498-a6812cad-8d94-43f2-83e4-0c92db6cfc91.png)

帮忙看看这个要怎么解决。

**Comment by kenzok8** [comment]
make distclean 
重新跑一次

**Comment by keivenliao** [comment]
> 

整个目录删了重新下的， 还是不行

**Comment by keivenliao** [comment]
> 

必须有啊

**Comment by keivenliao** [comment]
记录一下，刚才可以了。
