### ISSUE TITLE
openwrt-passwall自动切换中通过关键字添加、删除备用列表功能失效

### ISSUE THREAD

**Issue by ted-zheng** [kenzok8/openwrt-packages#370]
自动切换中通过关键字添加、删除备用列表功能失效，输入关键字添加或者删除都不能增加或者减少备用列表，每次列表有变化都只能一个个手动添加

多次重新编译最新版固件都是这样

希望有大神修复这个功能

日志无记录

![image](https://user-images.githubusercontent.com/45898071/218696450-aeae278d-5c86-4b98-985c-af66e44054fb.png)

luci-app-passwall 4.58
Google Chrome版本 110.0.5481.77（正式版本） （64 位）

**Comment by kenzok8** [comment]
请提交给作者

**Comment by ted-zheng** [comment]
> 请提交给作者

已经提交了，有人和我有一样的问题吗？
