### ISSUE TITLE
大佬，mosdns缺少upx/hos，更新了好几遍都这样

### ISSUE THREAD

**Issue by xiankaiyao** [kenzok8/openwrt-packages#372]
WARNING: Makefile 'package/feeds/kenzo/mosdns/Makefile' has a build dependency on 'upx/host', which does not exist
tmp/.config-package.in:63284:warning: config symbol defined without type

**Comment by kenzok8** [comment]
./scripts/feeds clean
./scripts/feeds update -a
./scripts/feeds install -a

**Comment by xiankaiyao** [comment]
> 

大佬，按这个更新了还是这个报错。用的li大的源码

**Comment by kenzok8** [comment]
报错是编译报Error 还是./scripts/feeds install报错信息，后面的不影响编译的

**Comment by xiankaiyao** [comment]
> 

install报错，那我再试试编译，谢谢大佬
