### ISSUE TITLE
sed: feeds.conf.default: No such file or directory

### ISSUE THREAD

**Issue by ChangAnCN** [kenzok8/openwrt-packages#373]
请问feeds.conf.default文件在哪个位置呢

**Comment by kenzok8** [comment]
lede的根目录，或者是openwrt的根目录
feeds.conf.default

**Comment by ChangAnCN** [comment]
十分感谢您的回复，我是用的是openwrt的官方镜像 设备是TPLINK c7v5 
ssh 进路由后 cd / && ls 
输出目录为：
root@OpenWrt:~# cd / && ls
bin      etc      mnt      proc     root     sys      usr      www
dev      lib      overlay  rom      sbin     tmp      var

并未发现feeds.conf.default文件。。

**Comment by kenzok8** [comment]
朋友，编译openwrt我建议你找个视频看看
1、非root用户
2、第三方软件库的拉取，基本原理你要了解

**Comment by ChangAnCN** [comment]
好的 我了解了 我去学习一下 感谢您的回复
