### ISSUE TITLE
 ERROR: package/feeds/kenzo/alist failed to build.

### ISSUE THREAD

**Issue by itbencn** [kenzok8/openwrt-packages#376]
执行`make download -j8`时
报错 
`ERROR: package/feeds/kenzo/alist failed to build.`

**Comment by itbencn** [comment]
这个错误在昨天就没有

**Comment by drangjchen** [comment]
我也一样是这个报错

**Comment by vividmuse** [comment]
运行命令安装 sudo apt-get update && sudo apt-get install -y libfuse-dev
