### ISSUE TITLE
passwall可以检测节点是否有效吗

### ISSUE THREAD

**Issue by han3sui** [kenzok8/openwrt-packages#38]
节点列表使用tcp检测延迟，不能确认这个节点是否能正常使用，只能一个一个节点尝试

**Comment by 18690819111** [comment]
好像只能检测是不是通的，有没有效还需要自己一个一个试，好像是

**Comment by han3sui** [comment]
> 好像只能检测是不是通的，有没有效还需要自己一个一个试，好像是

原作者在他issue回应了，需求实现很简单，不想做。
