### ISSUE TITLE
大佬能添加个msd_lite吗，替代udpxy，占用低了一个数量级

### ISSUE THREAD

**Issue by chnhhwz** [kenzok8/openwrt-packages#380]
大佬能添加个msd_lite吗，替代udpxy，占用低了一个数量级

**Comment by kenzok8** [comment]
[msd_lite] (https://github.com/kenzok8/small-package/blob/main/msd_lite)
[luci-app-msd_lite](https://github.com/kenzok8/small-package/tree/main/luci-app-msd_lite)
