### ISSUE TITLE
luci里的adguardhome下方的include binary不生效

### ISSUE THREAD

**Issue by ThingsWhy** [kenzok8/openwrt-packages#390]
测试了不论是否添加include binary这个参数，都不会影响编译adguardhome本体文件，还是得去network自己选adguardhome这个本体文件才会生效

**Comment by kenzok8** [comment]
那是luci 状态下include binary kenzo wu在 2023年4月16日，16:02，ThingsWhy ***@***.***> 写道：﻿
测试了不论是否添加include binary这个参数，都不会影响编译adguardhome本体文件，还是得去network自己选adguardhome这个本体文件才会生效
