### ISSUE TITLE
关于argonne主题的问题

### ISSUE THREAD

**Issue by ZiXia1** [kenzok8/openwrt-packages#393]
昨天一直在编译，直到下午的几个包发现argonne主题没起作用，发现下方修改将`argonne`改为了`argonnene`，所以这个修改是为了啥
https://github.com/kenzok8/openwrt-packages/commit/752afbde323c1ccc7f53e945101dfde99a572a5c#diff-89e669c96d353da8a5a2532bb4568d923f6157a39badb03dd487051f2985f0da
https://github.com/kenzok8/small-package/commit/612e1e0fc2efb1a38c32b193bd0c69870190fe4e#diff-89e669c96d353da8a5a2532bb4568d923f6157a39badb03dd487051f2985f0da

**Comment by kenzok8** [comment]
字符串替换时多按了一次，抱歉
