### ISSUE TITLE
云编译ipt2socks报错，hash值不匹配

### ISSUE THREAD

**Issue by aimetu** [kenzok8/openwrt-packages#395]
上游更新了hash值，麻烦同步下。
PKG_HASH:=5279eb1cb7555cf9292423cc9f672dc43e6e214b3411a6df26a6a1cfa59d88b7

**Comment by kenzok8** [comment]
https://github.com/kenzok8/small/commit/04371b7b3a9b5ff158d2aea2553ed24c67120ae6
