### ISSUE TITLE
luci-theme-argone能不能还原

### ISSUE THREAD

**Issue by Eay5** [kenzok8/openwrt-packages#396]
luci-theme-argone更新之后，太丑了，完全变了！能不能还原

**Comment by kenzok8** [comment]
截图看看

**Comment by Eay5** [comment]
是这样的,你这边的luci-theme-argon与https://github.com/jerrykuku/luci-theme-argon的不一样!最近你升级了,导致编译出的固件用以前的备份还原,系统就不能访问了.然后登录页界面也变了.

**Comment by Eay5** [comment]
谢谢你的源,我已经把那个主题给替换为了 https://github.com/jerrykuku/luci-theme-argon

**Comment by hatbhtbh** [comment]
> luci-theme-argone更新之后，太丑了，完全变了！能不能还原

之前的主题名称应该是：luci-theme-argonne替换了成了luci-theme-argone
现在的主题进入web管理，系统，管理权下有小图标显示不出的bug，需要修复或者还使用以前的主题
截图怎么上传不上来呢

**Comment by hatbhtbh** [comment]
请保留以前的主题风格，感谢！

**Comment by hatbhtbh** [comment]
> 谢谢你的来源，我已经把那个主题给替换为了https://github.com/jerrykuku/luci-theme-argon

请问你是怎么替换的，请指点一下，谢谢！

**Comment by hatbhtbh** [comment]
之前的主题名称是：luci-theme-argonne替换了成了luci-theme-argone
现在的主题进入web管理，系统，管理权下有小图标显示不出的bug，
需要修复或者还使用以前的主题

![9)4O9@ 4P8~9Z6IBK LOH4U](https://user-images.githubusercontent.com/93958708/236778031-1d2e49fc-1d06-4815-9d65-43b98492f4ce.png)

**Comment by kenzok8** [comment]
嗯，看到了，是bug，空了修复下

**Comment by Eay5** [comment]
> > 谢谢你的来源，我已经把那个主题给替换为了https://github.com/jerrykuku/luci-theme-argon
> 
> 请问你是怎么替换的，请指点一下，谢谢！

git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argonenew
在依赖里面加
然后主题改为luci-theme-argonenew,就好

**Comment by hatbhtbh** [comment]
> 嗯，看到了，是bug，空了修复下

大神，你昨天修复的是好了，又出现其它的问题，主菜单小图标出现问题，你看截图
![GW9_F4FM72 QM`2GDQXJPGV](https://github.com/kenzok8/openwrt-packages/assets/93958708/b2d777a0-e27f-45fe-8fcb-3551903bcfd9)
![A9Q42VPHS~XKGL%3R5W6Z06](https://github.com/kenzok8/openwrt-packages/assets/93958708/eb0cffc2-8fe3-4668-8579-c0dc4dec4e14)

**Comment by hatbhtbh** [comment]
> > 嗯，看到了，是bug，空了修复下
> 
> 大神，你昨天修复的是好了，又出现它的问题，主菜单小图标出现问题，你看截图 ![GW9_F4FM72 QM`2GDQXJPGV](https://user-images.githubusercontent.com/93958708/237251822-b2d777a0-e27f-45fe-8fcb-3551903bcfd9.png) ![A9Q42VPHS~XKGL%3R5W6Z06](https://user-images.githubusercontent.com/93958708/237251821-eb0cffc2-8fe3-4668-8579-c0dc4dec4e14.png)

**Comment by hatbhtbh** [comment]
> > > 嗯，看到了，是bug，空了修复下
> > 
> > 
> > 大神，你昨天修复的很好了，又出现其它的问题，主菜单小图标出现问题，你看截图![GW9_F4FM72 QM`2GDQXJPGV](https://user-images.githubusercontent.com/93958708/237251822-b2d777a0-e27f-45fe-8fcb-3551903bcfd9.png) ![A9Q42VPHS~XKGL%3R5W6Z06](https://user-images.githubusercontent.com/93958708/237251821-eb0cffc2-8fe3-4668-8579-c0dc4dec4e14.png)

**Comment by hatbhtbh** [comment]
> https://github.com/kenzok8/compile-package/releases 1 删除错误主题
> 
> opkg 信息 luci-theme* opkg 删除 luci-theme-argone
> 
> 2 openwrt主页系统下剩余的无效主题名称 nano /etc/config/luci
> 
> 3 /usr/lib/lua/luci/view/themes/ 目录下删除失效包

我今天再次用L大源码本地编译了一下，主题恢复如初，感谢~~~~~

**Comment by SpeedPartner** [comment]
看标题进来前,我还以为是我把18.06的改炸了...🤣
