### ISSUE TITLE
smartdns这个插件可以追踪最新源码更新吗？

### ISSUE THREAD

**Issue by smdx** [kenzok8/openwrt-packages#398]
大佬你好，smartdns这段时间源码修复很频繁，这个插件可以追踪最新源码更新而不是Release版本吗？谢谢

**Comment by kenzok8** [comment]
我不太理解你的要求，如果是Release版本应该属于最稳定的发布版本，如果你光追求每一次他代码更新就随着更新，可能会有bug，如果你是最求最新的每一次提交就更新，那就找这个仓库
https://github.com/kenzok8/jell/tree/main/smartdns
这个仓库是主要每一次提交他都会自动更新

**Comment by smdx** [comment]
感谢
