### ISSUE TITLE
某次更新后，缺少相关软件包

### ISSUE THREAD

**Issue by namas0312** [kenzok8/openwrt-packages#399]
大神：
原本您的github内含有的软件包，在更新之后，我现在编译，在make menuconfig中找不到软件，之前是有的，麻烦协助：

luci-app-bandwidthd
luci-app-linkease
luci-app-netspeedtest
luci-app-oaf
luci-app-poweroff

**Comment by kenzok8** [comment]
你说的https://github.com/kenzok8/small-package/tree/main/luci-app-bandwidthd都有，这个仓库一直致力干净整洁

**Comment by namas0312** [comment]
@kenzok8 大佬，目前我仅额外添加small-package的git地址后，编译含有netdata和netspeednest，就一直报错，请问是我添加的地址不完整导致的么
