### ISSUE TITLE
用L大的 21.02的源码，主题都用不了，dockerman也有问题

### ISSUE THREAD

**Issue by xiaoqi2020** [kenzok8/openwrt-packages#400]
除了默认的外，启用任何主题都UI报错
dockerman也有问题，只有一个配置项，没有其他的设置项
![image](https://github.com/kenzok8/openwrt-packages/assets/50669177/d5d48dd3-c2fb-46de-9add-8ad989897765)

**Comment by kenzok8** [comment]
里面的主题本来就是不支持21.02
