### ISSUE TITLE
null

### ISSUE THREAD

**Issue by NianBroken** [kenzok8/openwrt-packages#401]
null

**Comment by cjwddtc** [comment]
首先欧盟就不可能出和翻墙有关的东西，和匿名有关的倒是有。

其次这是一个四级域名，主站四级域名说明搭网站的人连域名的钱都不愿意出。

点进去就能看到这就是一个推荐机场的网页，链接点进去有邀请码，赚aff的网页而已。

这里是openwrt仓库不是翻墙论坛，不要发无关的东西。
