### ISSUE TITLE
adguardhome无法使用

### ISSUE THREAD

**Issue by xiaoqi2020** [kenzok8/openwrt-packages#402]
核心下载了也一直提示找不到核心，但是核心是已经下载成功的，首次保存配置可以，二次保存就一直提示 执行文件路径 有问题了 error!bin path is a dir
![image](https://github.com/kenzok8/openwrt-packages/assets/50669177/86fd2037-b2dc-4d3e-8bf6-706f9f71c508)

**Comment by wordscode** [comment]
我也是

**Comment by wordscode** [comment]
![image](https://github.com/kenzok8/openwrt-packages/assets/75980075/9f0f138b-a47c-42b0-81ac-91767dec421b)
好像就改一个执行文件路径就可以了
