### ISSUE TITLE
luci-app-fileassistant编译出来不显示文件列表

### ISSUE THREAD

**Issue by anjue39** [kenzok8/openwrt-packages#407]
用最新lede源码，添加源后，luci-app-fileassistant编译出来不显示文件列表

**Comment by kenzok8** [comment]
luci/applications/luci-app-filetransfer 删除源码自带的

**Comment by kenzok8** [comment]
https://github.com/kenzok8/openwrt-packages/commit/eb7eab0edbc597798ce74818d8f4330319f0e200

**Comment by kenzok8** [comment]
你卸载软件，到我的仓库下载了安装试试
https://op.dllkids.xyz/packages/x86_64/luci-app-fileassistant_git-24.121.56352-d7b4d99_all.ipk

**Comment by anjue39** [comment]
> 你卸载软件，到我的仓库下载了安装试试 https://op.dllkids.xyz/packages/x86_64/luci-app-fileassistant_git-24.121.56352-d7b4d99_all.ipk

kenzok78里已开始修复，确实有问题

**Comment by anjue39** [comment]
![image](https://github.com/kenzok8/openwrt-packages/assets/98279987/6e1644f5-29b7-4fe7-949f-4c3b176bfe76)
