### ISSUE TITLE
luci-theme-opentomato 主题无法使用，首页都打不开

### ISSUE THREAD

**Issue by doumeki** [kenzok8/openwrt-packages#41]
LEAN 的17.01分支https://github.com/coolsnowwolf/openwrt 

OpenWrt
Loading...
未设置密码！

尚未设置密码。请为 root 用户设置密码以保护主机并启用 SSH。
Status: 500 Internal Server Error /usr/lib/lua/luci/dispatcher.lua:381: Failed to execute function dispatcher target for entry '/'. The called action terminated with an exception: /usr/lib/lua/luci/template.lua:55: Failed to execute template 'sysauth'. A runtime error occured: /usr/lib/lua/luci/template.lua:55: Failed to execute template 'header'. A runtime error occured: /usr/lib/lua/luci/template.lua:55: Failed to execute template 'themes/opentomato/header'. A runtime error occured: [string "/usr/lib/lua/luci/view/themes/opentomato/he..."]:138: attempt to call field 'lookup' (a nil value) stack traceback: [C]: in function 'assert' /usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch' /usr/lib/lua/luci/dispatcher.lua:95: in function

**Comment by kenzok8** [comment]
使用说明上已经标注了适配18.06的luci

**Comment by doumeki** [comment]
我没理解错的话，这个应该是18.06的LUCI。

src-git luci https://github.com/coolsnowwolf/luci

**Comment by kenzok8** [comment]
对头

kenzo wu

**Comment by doumeki** [comment]
所以，这个17.01的feeds 用的就是18.06的LUCI，结果报错。
