### ISSUE TITLE
能否增加一款主题luci-theme-rosy

### ISSUE THREAD

**Issue by x2287711259** [kenzok8/openwrt-packages#410]
希望增加一款主题luci-theme-rosy，自己觉得很好看，但是找不到ipk插件包，希望能支持mipsel_24kc架构
https://github.com/rosywrt/luci-theme-rosy

**Comment by magi-Z** [comment]
拉源码编译一下！

**Comment by kenzok8** [comment]
https://op.dllkids.xyz/packages/mipsel_24kc/luci-theme-rosy_git-24.222.17391-69ecc83_all.ipk
