### ISSUE TITLE
luci-app-filebrowser

### ISSUE THREAD

**Issue by qq1316237299** [kenzok8/openwrt-packages#421]
luci-app-filebrowser编译没luci界面

**Comment by qq1316237299** [comment]
谢谢大佬，这么快就修复了

**Comment by qq1316237299** [comment]
上一个编译可以  现在更新的这个编译出错

**Comment by qq1316237299** [comment]
![image](https://github.com/kenzok8/openwrt-packages/assets/42686656/b03834bc-0b78-43b7-89ed-e89be0e87edb)

**Comment by qq1316237299** [comment]
[update 2023-10-12 17:18:01](https://github.com/kenzok8/openwrt-packages/commit/052dabf7bebae820f6e66442a0dfb899ec2e6528) 这个更新的是可以正常编译使用

**Comment by kenzok8** [comment]
好的，我去修复

**Comment by qq1316237299** [comment]
> 好的，我去修复

谢谢大佬
