### ISSUE TITLE
AdGuard Home 界面显示有BUG

### ISSUE THREAD

**Issue by xysck** [kenzok8/openwrt-packages#422]
当更新到0.107.39版本时，原界面显示有bug，“重定向”显示为“6060重定向”。

**Comment by chenmozhijin** [comment]
我修过这个问题 https://github.com/chenmozhijin/luci-app-adguardhome/commit/5d1bf40ddea96ba401dda68161e02fdc6512d7e2

**Comment by 1-1-2** [comment]
https://github.com/kenzok8/openwrt-packages/blob/67a1e565c46f5071927095cce02b11685f26da6f/luci-app-adguardhome/luasrc/model/cbi/AdGuardHome/base.lua#L59

修改为
```lua
local port=luci.sys.exec("awk '/^dns:$/,/ port:/ { if ($1 == "port:") {print $2;exit;} }' "..configpath.." 2>nul")
```
试试
