### ISSUE TITLE
WARNING: Makefile 'package/feeds/kenzo/luci-app-wechatpush/Makefile' has a dependency on 'wrtbwmon', which does not exist

### ISSUE THREAD

**Issue by qq1316237299** [kenzok8/openwrt-packages#429]
WARNING: Makefile 'package/feeds/kenzo/luci-app-wechatpush/Makefile' has a dependency on 'wrtbwmon', which does not exist
![image](https://github.com/kenzok8/openwrt-packages/assets/42686656/cad7dd76-cc5e-47fd-ab87-422d18c7be4a)

**Comment by Copox** [comment]
请问你是如何解决的?

**Comment by qq1316237299** [comment]
> 请问你是如何解决的?

删库

**Comment by jianxtop** [comment]
@qq1316237299 请问如何删库
