### ISSUE TITLE
#BUG Passwall日志内存溢出导致opkg update fail return 3

### ISSUE THREAD

**Issue by magictomagic** [kenzok8/openwrt-packages#452]
这个日志如果不关的话会一直写入TCP.log文件然后把挂在在/tmp上的tmpfs写满导致opkg update失败
![image](https://github.com/kenzok8/openwrt-packages/assets/59344440/3249a3d7-c248-43fa-9178-bcc171d091b3)

加一个清理日志或持久化日志的默认配置

**Comment by INTEL-2333** [comment]
https://github.com/xiaorouji/openwrt-passwall/discussions
