### ISSUE TITLE
编译passwall出错

### ISSUE THREAD

**Issue by hztbhtbh** [kenzok8/openwrt-packages#456]
编译passwall出错，如下：
`Finding targets`
`go: ../../go.mod requires go >= 1.22 (running go 1.21.5; GOTOOLCHAIN=local)`
`Building targets`
`go: ../../go.mod requires go >= 1.22 (running go 1.21.5; GOTOOLCHAIN=local)`
`Finding targets`
`go: ../../go.mod requires go >= 1.22 (running go 1.21.5; GOTOOLCHAIN=local)`
`Building targets`
`go: ../../go.mod requires go >= 1.22 (running go 1.21.5; GOTOOLCHAIN=local)`
`make[3]: *** [Makefile:44: /home/tbh/lede/build_dir/target-x86_64_musl/v2ray-plugin-5.14.1/.built] Error 1`
`make[3]: Leaving directory '/home/tbh/lede/feeds/small/v2ray-plugin'`
`time: package/feeds/small/v2ray-plugin/compile#0.28#0.31#0.54`
`ERROR: package/feeds/small/v2ray-plugin failed to build.`
`make[2]: *** [package/Makefile:116: package/feeds/small/v2ray-plugin/compile] Error 1`
`make[2]: Leaving directory '/home/tbh/lede'`
`make[1]: *** [package/Makefile:110: /home/tbh/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2`
`make[1]: Leaving directory '/home/tbh/lede'`
`make: *** [/home/tbh/lede/include/toplevel.mk:231: world] Error 2`

**Comment by hztbhtbh** [comment]
[已经有大佬解决，感谢大佬........]
此方法是正对ubuntu22.04版本拉取lean的lede源代码编译的固件：
https://github.com/xiaorouji/openwrt-passwall/discussions/2969

**Comment by Bpc-CPU** [comment]
不用复制的-->[https://github.com/xiaorouji/openwrt-passwall/discussions/2969](https://github.com/xiaorouji/openwrt-passwall/discussions/2969)
