### ISSUE TITLE
dockerman 的网络无法打开

### ISSUE THREAD

**Issue by woni928** [kenzok8/openwrt-packages#461]
![Screenshot_2024-03-16-22-50-11-296_mark via](https://github.com/kenzok8/openwrt-packages/assets/28220733/5e5bf72b-4594-43c1-94dd-05fc478ab1fe)

这个没有提交过？
https://github.com/lisaac/luci-app-dockerman/commit/7292955a1b415bb60fa2e403bb3a437b4b7f7846

**Comment by kenzok8** [comment]
已更新https://github.com/lisaac/luci-app-dockerman/commit/7292955a1b415bb60fa2e403bb3a437b4b7f7846
