### ISSUE TITLE
package/feeds/kenzo/adguardhome failed to build

### ISSUE THREAD

**Issue by woni928** [kenzok8/openwrt-packages#462]
2024-0321-云编译报错

![2024-03-21_141550](https://github.com/kenzok8/openwrt-packages/assets/28220733/4ed9e266-b251-4339-a22d-ba43aff234a3)

**Comment by kenzok8** [comment]
编译没问题的哦，你是刚刚编译的？
https://github.com/kenzok8/compile-package/releases/tag/2024.03.21-10%2F17_aarch64_generic

**Comment by woni928** [comment]
> 编译没问题的哦，你是刚刚编译的？ https://github.com/kenzok8/compile-package/releases/tag/2024.03.21-10%2F17_aarch64_generic

今天13点左右编译的，出现的问题，前5天编译过很正常。

**Comment by woni928** [comment]
刚才又编译了下，还是报错。

**Comment by kenzok8** [comment]
#463

**Comment by woni928** [comment]
> #463

谢谢 已经正常
