### ISSUE TITLE
编译总是adguardhome出错！

### ISSUE THREAD

**Issue by magi-Z** [kenzok8/openwrt-packages#463]
make[3]: Entering directory '/home/magi/lede/feeds/kenzo/adguardhome'
touch /home/magi/lede/build_dir/target-aarch64_generic_musl/adguardhome-0.107.46/.prepared_415390861d6ac542e0b4daa98f462e7c_6664517399ebbbc92a37c5bb081b5c53_check
. /home/magi/lede/include/shell.sh; /home/magi/lede/staging_dir/host/bin/libdeflate-gzip -dc /home/magi/lede/dl/adguardhome-0.107.46.tar.gz | tar -C /home/magi/lede/build_dir/target-aarch64_generic_musl/adguardhome-0.107.46/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/magi/lede/build_dir/target-aarch64_generic_musl/adguardhome-0.107.46
if [ -d "/home/magi/lede/build_dir/target-aarch64_generic_musl/AdGuardHome-0.107.46" ]; then mv "/home/magi/lede/build_dir/target-aarch64_generic_musl/AdGuardHome-0.107.46/"* "/home/magi/lede/build_dir/target-aarch64_generic_musl/adguardhome-0.107.46/"; fi
if [ -d "/home/magi/lede/build_dir/target-aarch64_generic_musl/AdGuardHome-0.107.46" ]; then mv "/home/magi/lede/build_dir/target-aarch64_generic_musl/AdGuardHome-0.107.46/"* "/home/magi/lede/build_dir/target-aarch64_generic_musl/adguardhome-0.107.46/"; fi
mv: cannot stat '/home/magi/lede/build_dir/target-aarch64_generic_musl/AdGuardHome-0.107.46/*': No such file or directory
make[3]: *** [Makefile:98: /home/magi/lede/build_dir/target-aarch64_generic_musl/adguardhome-0.107.46/.prepared_415390861d6ac542e0b4daa98f462e7c_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/magi/lede/feeds/kenzo/adguardhome'
time: package/feeds/kenzo/adguardhome/compile#0.24#0.15#0.40
    ERROR: package/feeds/kenzo/adguardhome failed to build.
make[2]: *** [package/Makefile:116: package/feeds/kenzo/adguardhome/compile] Error 1
make[2]: Leaving directory '/home/magi/lede'
make[1]: *** [package/Makefile:110: /home/magi/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/magi/lede'
make: *** [/home/magi/lede/include/toplevel.mk:231：world] 错误 2

**Comment by woni928** [comment]
差不多同样的错误 等待k佬修复
