### ISSUE TITLE
UnblockNeteaseMusic 

### ISSUE THREAD

**Issue by magi-Z** [kenzok8/openwrt-packages#468]
make[3]: *** [Makefile:48: /home/magi/lede/dl/UnblockNeteaseMusic-.tar.gz] Error 255
make[3]: Leaving directory '/home/magi/lede/feeds/kenzo/UnblockNeteaseMusic'
time: package/feeds/kenzo/UnblockNeteaseMusic/compile#0.16#0.02#0.18
    ERROR: package/feeds/kenzo/UnblockNeteaseMusic failed to build.
make[2]: *** [package/Makefile:116: package/feeds/kenzo/UnblockNeteaseMusic/compile] Error 1

**Comment by kenzok8** [comment]
嗯，源码中有点小错 已经修复[#d738a58](url)
