### ISSUE TITLE
luci-app-filebrowser编译没luci界面

### ISSUE THREAD

**Issue by hztbhtbh** [kenzok8/openwrt-packages#472]
luci-app-filebrowser编译成功后没luci界面
使用Lean的LEDE源代码编译的X86固件，请大佬指点一下，谢谢！

**Comment by iHub-2020** [comment]
我也遇到了同样的问题，请问是如何解决的？谢谢

**Comment by hztbhtbh** [comment]
没有解决，不会，已经弃用了

**Comment by iHub-2020** [comment]
好的，谢谢

**Comment by kenzok8** [comment]
试试这个版本看看

**Comment by hztbhtbh** [comment]
> 试试这个版本看看

谢谢了，不过更新后单线程编译报错了，算了也不是非用不可
![2](https://github.com/kenzok8/openwrt-packages/assets/104251804/f4cb6989-9332-46db-b4c0-b92c3acd12f7)

**Comment by kenzok8** [comment]
https://github.com/kenzok8/litte/releases/tag/155-x86_64

**Comment by iHub-2020** [comment]
用我的版本，已经成功了，注意：不需要filebrowser依赖包，否则会冲突。
https://github.com/iHub-2020/openwrt-reyan/tree/main/luci-app-filebrowser
