### ISSUE TITLE
op.dllkids.xyz 的证书已于 2024/5/31 过期

### ISSUE THREAD

**Issue by hy741oo** [kenzok8/openwrt-packages#474]
今天我在更新opkg源的时候提示我该源的Packages.gz下载失败，我用浏览器登录就提示我网站的证书已经过期：
![屏幕截图 2024-06-01 084933](https://github.com/kenzok8/openwrt-packages/assets/74581320/a9a68759-3f6f-49cf-b5eb-5ee123ee2bde)

**Comment by bilibili2077** [comment]
证书过期了，我也更新不了！

**Comment by iocscix** [comment]
前一秒还在用，后一秒就更新了，还有类似的可以直接用来在线安装的passwall的源吗

**Comment by kenzok8** [comment]
已经修复了
