### ISSUE TITLE
[Package Request] openwrt-frp

### ISSUE THREAD

**Issue by luochen1990** [kenzok8/openwrt-packages#476]
URL: https://github.com/kuoruan/openwrt-frp

Reason:   This project is very useful, but this repo doesn't provide mipsel_24kc package.

**Comment by kenzok8** [comment]
这个库存不打算再添加了，如果觉得插件不够，请移步到[small-package](https://github.com/kenzok8/small-package)

**Comment by luochen1990** [comment]
thanks for telling this
