### ISSUE TITLE
luci-app-smartdns更新

### ISSUE THREAD

**Issue by AXBNG** [kenzok8/openwrt-packages#477]
官方已发布release 46，仓库luci还停留在45，大佬有空更新下~

**Comment by kenzok8** [comment]
我看了下是内核更新 就是smartdns，作者的luci本地仓库没有更新，可能就是编译时命名规则而已吧

**Comment by AXBNG** [comment]
> 我看了下是内核更新 就是smartdns，作者的luci本地仓库没有更新，可能就是编译时命名规则而已吧

哦吼貌似是的，那没事了大佬~
