### ISSUE TITLE
大佬，adguardhome更新后又编译出错了

### ISSUE THREAD

**Issue by smdx** [kenzok8/openwrt-packages#480]
大佬，adguardhome更新后今天早上编译又出错了。请问怎么解决？谢谢

![2024-07-05_104103](https://github.com/kenzok8/openwrt-packages/assets/9279217/9138137b-e8d9-4349-9a18-4be33ffd134e)

**Comment by smdx** [comment]
@kenzok8
大佬，7号的更新还是编译不了
![2024-07-07_120814](https://github.com/kenzok8/openwrt-packages/assets/9279217/ec3c3ea3-ab49-41fd-9749-7e220eee06b5)

go用的是：
rm -rf feeds/packages/lang/golang
git clone https://github.com/kenzok8/golang feeds/packages/lang/golang

**Comment by kenzok8** [comment]
adguardhome编译依赖golang ，然后golang没更新，现在已经更新ceb724d0aaffb70fd70463ba476e818297cd0100
应该编译没问题了

**Comment by smdx** [comment]
好的，谢谢
