### ISSUE TITLE
2024.7.18 chinadns-ng，源代码不存在

### ISSUE THREAD

**Issue by lanruihua026** [kenzok8/openwrt-packages#486]
<img width="951" alt="屏幕截图 2024-07-18 204020" src="https://github.com/user-attachments/assets/85709c69-26f1-4a98-8413-70f667f1092b">
<img width="1280" alt="屏幕截图 2024-07-18 205410" src="https://github.com/user-attachments/assets/b5b2bb57-1503-4c32-a727-2d8f30b89fca">

如上图所示，今天编译3次均是该源代码不存在，浏览器点开画线url提示404，希望大佬能更新修复一下

**Comment by lanruihua026** [comment]
编译采用github action云编译

**Comment by kenzok8** [comment]
这个你应该提交到small仓库，是hash值错了，已经修复https://github.com/kenzok8/small/commit/f29b3155e33d10924bbbfac0dc070bcb6bfb999d
