### ISSUE TITLE
mosdns编译出错

### ISSUE THREAD

**Issue by star8618** [kenzok8/openwrt-packages#487]
* check_data_file_clashes: Package luci-app-mosdns wants to install file /home/jacky/immortalwrt/build_dir/target-x86_64_musl/root-x86/etc/init.d/mosdns
        But that file is already provided by package  * mosdns
 * opkg_install_cmd: Cannot install package luci-app-mosdns.
 * check_data_file_clashes: Package luci-app-mosdns wants to install file /home/jacky/immortalwrt/build_dir/target-x86_64_musl/root-x86/etc/init.d/mosdns
        But that file is already provided by package  * mosdns
 * opkg_install_cmd: Cannot install package luci-i18n-mosdns-zh-cn.
make[2]: *** [package/Makefile:71: package/install] Error 255
make[2]: Leaving directory '/home/jacky/immortalwrt'
make[1]: *** [package/Makefile:124: /home/jacky/immortalwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/jacky/immortalwrt'
make: *** [/home/jacky/immortalwrt/include/toplevel.mk:232: world] Error 2

**Comment by ljkk-li** [comment]
alist 3.36.0也编译错误

**Comment by kenzok8** [comment]
golang 1.22.5去编译

**Comment by ljkk-li** [comment]
> golang 1.22.5去编译

谢谢
