### ISSUE TITLE
homeproxy插件和luci-app-homeproxy插件是重复的。

### ISSUE THREAD

**Issue by Azreulo** [kenzok8/openwrt-packages#489]
首先homeproxy插件是调用sing-box和chingdns-ng，所以其实只是一个luci界面，依赖里也没有别的了。

然后我对比了一下homeproxy插件和luci-app-homeproxy插件，发现文件都一样，就多了一个README文件。建议删掉homeproxy，保留luci-app-homeproxy。

**Comment by kenzok8** [comment]
谢谢提醒，拉去时没注意
