### ISSUE TITLE
某些依赖包下载地址为国内源，导致海外VPS下载失败

### ISSUE THREAD

**Issue by zhucaidan** [kenzok8/openwrt-packages#49]
某些依赖包下载地址为国内源，导致海外VPS下载失败
ustclug.org开头的，好像是国内大学源，如何能替换全部为海外源呢？

**Comment by 02015678** [comment]
应该与本项目无关吧。
源码根目录feeds.conf.default文件里，建议将其他src-git源的镜像从ustclug.org换成其他源。

另外看看你的.config文件里的这一样写的是啥
`CONFIG_VERSION_REPO="http://downloads.openwrt.org/releases/19.07.1"`
