### ISSUE TITLE
luci-app-alist版本问题导致op的web不显示插件入口

### ISSUE THREAD

**Issue by LIUBANGJIAN** [kenzok8/openwrt-packages#490]
大佬，你好。我的用的源再加上L大的op源在线编译op。现在luci-app-alist升级新版本后，用的是luci2导致op的web页面不显示插件入口。请问比较好的解决方案吗？

相关问题的issues如下，麻烦看看。谢谢
https://github.com/sbwml/luci-app-alist/issues/124

**Comment by LIUBANGJIAN** [comment]
感觉这个问题也是石沉大海

**Comment by kenzok8** [comment]
这两天在国外，回去了我看看

**Comment by LIUBANGJIAN** [comment]
大佬 辛苦了

**Comment by kenzok8** [comment]
作者已经说明 openwrt-18.06 或更旧的 OpenWrt 无法使用，建议更换[Lienol的23.05分支](https://github.com/Lienol/openwrt) 或者[immortalwrt的23.05分支](https://github.com/immortalwrt/immortalwrt)

**Comment by LIUBANGJIAN** [comment]
好东西，多谢大佬的技术支持。

**Comment by LIUBANGJIAN** [comment]
大佬，请问以后的库都不更新luci-app-alist的版本了吗？
