### ISSUE TITLE
hysteria无法编译，提示no Go files in /mnt/build/lede/build_dir/target-x86_64_musl/hysteria-app-v2.5.1/.go_work/build

### ISSUE THREAD

**Issue by zhaxingyu** [kenzok8/openwrt-packages#495]
Finding targets
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.

Building targets
no Go files in /mnt/build/lede/build_dir/target-x86_64_musl/hysteria-app-v2.5.1/.go_work/build

make[2]: *** [Makefile:62: /mnt/build/lede/build_dir/target-x86_64_musl/hysteria-app-v2.5.1/.built] Error 1
make[2]: Leaving directory '/mnt/build/lede/feeds/small/hysteria'
time: package/feeds/small/hysteria/compile#0.30#0.27#0.48
    ERROR: package/feeds/small/hysteria failed to build.
make[1]: *** [package/Makefile:116: package/feeds/small/hysteria/compile] Error 1
make[1]: Leaving directory '/mnt/build/lede'
make: *** [/mnt/build/lede/include/toplevel.mk:231：package/feeds/small/hysteria/compile] 错误 2

**Comment by kenzok8** [comment]
稍等 golang 需要更新了，等下更新
