### ISSUE TITLE
编译时报依赖不存在错误

### ISSUE THREAD

**Issue by xujianjie1213** [kenzok8/openwrt-packages#5]
![1](https://user-images.githubusercontent.com/35050408/79707626-bc874e00-82ef-11ea-93c4-ff56fad7ea79.png)
外部命令引入，menu里能看到插件，但是编译的时候报not exsit错误

**Comment by kenzok8** [comment]
看我说明，passwall有依赖库链接，下载放进你目录或者新建目录都可以

kenzo 小猪班尼

**Comment by xujianjie1213** [comment]
抱歉，之前漏看了，那smartdns的问题呢？
