### ISSUE TITLE
编译PASSWALL，已经选择了trojan支持，但是编译完导入trojan节点 解析不了无法导入。。。。

### ISSUE THREAD

**Issue by slayercjc** [kenzok8/openwrt-packages#52]
编译PASSWALL，已经选择了trojan支持，但是编译完导入trojan节点 解析不了无法导入。。。。请问作者是什么原因呢？
![微信截图_20200830225325](https://user-images.githubusercontent.com/14236188/91662891-e2332800-eb17-11ea-9881-851576733884.png)
![微信截图_20200830225346](https://user-images.githubusercontent.com/14236188/91662895-e65f4580-eb17-11ea-9da6-989caca24e05.png)

**Comment by zhucaidan** [comment]
在节点管理界面直接导入trojan链接就行了，不要在新建节点内部导入会失败的
