### ISSUE TITLE
SSR缺少依赖

### ISSUE THREAD

**Issue by brianzc** [kenzok8/openwrt-packages#54]
WARNING: Makefile 'package/feeds/kenzo/luci-app-ssr-plus/Makefile' has a dependency on 'naiveproxy', which does not exist

**Comment by o-water-o** [comment]
我也是这个情况编译不通过

**Comment by Eveaz** [comment]
这是由于kenzok8大佬，没有把helloworld的文件都拷过来。
先编辑feeds.conf.default
```
#src-git kenzo https://github.com/kenzok8/openwrt-packages
src-git helloworld https://github.com/fw876/helloworld
```
然后 ./scripts/feeds update -a 以及 ./scripts/feeds install -a
再编辑feeds.conf.default
```
src-git kenzo https://github.com/kenzok8/openwrt-packages
#src-git helloworld https://github.com/fw876/helloworld
```
然后再编译。

**Comment by o-water-o** [comment]
> 这是由于kenzok8大佬，没有把helloworld的文件都拷过来。
> 先编辑feeds.conf.default
> 
> ```
> #src-git kenzo https://github.com/kenzok8/openwrt-packages
> src-git helloworld https://github.com/fw876/helloworld
> ```
> 
> 然后 ./scripts/feeds update -a 以及 ./scripts/feeds install -a
> 再编辑feeds.conf.default
> 
> ```
> src-git kenzo https://github.com/kenzok8/openwrt-packages
> #src-git helloworld https://github.com/fw876/helloworld
> ```
> 
> 然后再编译。

把helloworld 源直接放开，一起编译不行么
