### ISSUE TITLE
总是出现这错误，怎么解决

### ISSUE THREAD

**Issue by wwz09** [kenzok8/openwrt-packages#64]
WARNING: Makefile 'package/feeds/luci/luci-app-https-dns-proxy/Makefile' has a dependency on 'https-dns-proxy', which does not exist

**Comment by kenzok8** [comment]
openwrt源码仓库自带的的https-dns-proxy版本太旧，而passwall需要的是新版的https-dns-proxy

kenzo wu

> 在 2020年9月25日，23:02，wwz09 <notifications@github.com> 写道：
> 
> WARNING: Makefile 'package/feeds/luci/luci-app-https-dns-proxy/Makefile' has a dependency on 'https-dns-proxy', which does not exist
