### ISSUE TITLE
jd签到还是0.84

### ISSUE THREAD

**Issue by tzxiaozhen88** [kenzok8/openwrt-packages#66]
jd签到还是0.84编译后 不能签到更新下把

**Comment by tzxiaozhen88** [comment]
我1号编译时候拉的是0.85的  现在变成0.84了  倒着更新了晕

**Comment by kenzok8** [comment]
git clone https://github.com/jerrykuku/luci-app-jd-dailybonus.git  你可以自己去老竭力仓库下载，但是0.85编译时有点问题的，不稳定，所以我回退到0.84了！

**Comment by tzxiaozhen88** [comment]
我删了node-request依赖     0.85编译通过没问题
