### ISSUE TITLE
Advanced Setting 能否显示成中文菜单

### ISSUE THREAD

**Issue by zxjack** [kenzok8/openwrt-packages#74]
使用您的源码编译了Advanced Setting，在菜单界面中显示的是英文，请问是否能够显示成中文呢？
![Snipaste_2020-10-28_10-24-32](https://user-images.githubusercontent.com/9455090/97383125-d7262980-1907-11eb-9517-acbba3b21559.png)

**Comment by doumeki** [comment]
简单， 把/feeds/kenzo/luci-app-advancedsetting/po/ 下的 zh_Hans 改名为 zh-cn
