### ISSUE TITLE
Google无果，想问下为什么斐讯K3不支持src-git

### ISSUE THREAD

**Issue by gricn** [kenzok8/openwrt-packages#83]
实在不好意思在这提问，但中英文Google了很久`src-git` / `src/gz` 都没有找到相关资料。
为什么斐讯K3的软件源只支持src/gz呢，这样没法使用该软件或订阅软件包。我需要重新回到cfe然后通过刷lede的manifest包来实现`src-git`吗？（今晚已编译lede最新版本）

**Comment by kenzok8** [comment]
自定义软件源 建议去看esir的油管视频

**Comment by gricn** [comment]
非常感谢~~ @kenzok8

**Comment by gricn** [comment]
在这个YouTube视频中解释了这个东东，原来是二次编译时使用的
https://www.youtube.com/watch?v=35ImdukpmyY&ab_channel=eSirPlayGround
