### ISSUE TITLE
passwall已经恢复更新了，passwall的仓库的owner已经从Lienol转移给xiaorouji，请问作者，你仓库里的passwall是同步 xiaorouji 的吗？

### ISSUE THREAD

**Issue by chpos** [kenzok8/openwrt-packages#88]
passwall已经恢复更新好久了，现在还有些人消息闭塞，继续传播错误信息……passwall的仓库的owner已经从Lienol转移给xiaorouji了，新的passwall仓库地址在下方👇
https://github.com/xiaorouji/openwrt-package

**Comment by kenzok8** [comment]
答案是肯定的

**Comment by chpos** [comment]
谢谢
