### ISSUE TITLE
passwall 20201204版不能使用Xray、V2ray请尽快修复

### ISSUE THREAD

**Issue by tianiue** [kenzok8/openwrt-packages#92]
passwall 20201204版编译Xray、V2ray，不显示版本号，更新也不能保存，请尽快修复

**Comment by lexin8** [comment]
最近删除了passwall以及SSR重新添加，现在问题很多，V2ray直接没有了。

**Comment by tianiue** [comment]
看有人说了这个方法：
组件更新处不能获取已安装的版本，分析原因为程序路径错误，需要指定到/usr/bin/xray/xray或者/usr/bin/v2ray/v2ray

**Comment by lexin8** [comment]
> 看有人说了这个方法：
> 组件更新处不能获取已安装的版本，分析原因为程序路径错误，需要指定到/usr/bin/xray/xray或者/usr/bin/v2ray/xray

刚刚才编译出炉的，/usr/bin/路径下没有xray以及xray

**Comment by chpos** [comment]
我也遇到了类似的问题，麻烦辛苦一下作者修复一下
