### ISSUE TITLE
AdguardHome和Luci-app-adguardhome问题

### ISSUE THREAD

**Issue by Gabrielxzx** [kenzok8/openwrt-packages#97]
路由器型号：Xunlong Orange Pi Zero
固件版本：OpenWrt R20.12.12 / LuCI Master (git-20.343.54716-6fc079f)
故障现象：
1.若编译时不选择AdguardHome，则初次使用Luci-app-adguardhome时无法下载更新，更新后显示   核心版本:error，手动替换后可正常使用，情况如下图

![屏幕截图 2021-01-03 095307](https://user-images.githubusercontent.com/27126997/103470187-12325680-4daa-11eb-94a5-57efa5cadeef.png)

2.编译时加入AdguardHome，Luci-app-adguardhome可正常显示核心版本0.104.3，但无法通过3000端口打开配置界面。打开配置界面时显示404，情况如下图。

![屏幕截图 2021-01-03 095400](https://user-images.githubusercontent.com/27126997/103470194-270eea00-4daa-11eb-9856-c99052d00dab.png)

3.经过检查，发现通过编译生成的核心比adguardhome官方放出的核心体积小，不清楚是不是这个导致的问题。

**Comment by doumeki** [comment]
同样，报的404错误。看了下downloads下载的不对。没有从github上下。

**Comment by Gabrielxzx** [comment]
> 同样，报的404错误。看了下downloads下载的不对。没有从github上下。

编译时通过files大法进行替代，也算是一种解决问题的方式
