### ISSUE TITLE
希望加入解锁网易云UnblockNeteaseMusic

### ISSUE THREAD

**Issue by haswelliris** [kenzok8/openwrt-packages#98]
Lean的UnblockNeteaseMusic包好像没有被包含进来，希望能加入   
[UnblockNeteaseMusic](https://github.com/coolsnowwolf/lede/tree/master/package/lean/UnblockNeteaseMusic  )
[UnblockNeteaseMusicGo](https://github.com/coolsnowwolf/lede/tree/master/package/lean/UnblockNeteaseMusicGo)

**Comment by Carrjiang** [comment]
实际上，在两个版本中都内置了网易云音乐解锁服务，不过需要自行开启

**Comment by haswelliris** [comment]
行吧，因为我是用的官方源，我把他们的package再塞进来好了
